### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by bmcbride** [jdorn/json-editor#158]
I'm having some issues figuring out how to make a field required. I've tried the [following](http://jeremydorn.com/json-editor/?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIJaWZaksGioOAhgFtyoMKXIgMYNBBwBzJgBMudaSUi5EIAGIRMYAAR8cC/QBk+k/fyFMBM07DlgAFogAshJQDM+AV2iMSABS6LACRPoAIlhoeAC+hHyywsRkmjJgsMloirA+/oEATB4gdjgQAr4CiACMAByEAnwAHhVViACcHQkgdFgCQjiBImKaktJyTF4xTYHgsM1gfGiwfCA9PgBuMVCwAPp90DE8qeLjMvKE02izmofHhJAw4ls7mfr3OZ55fgGaAMReHwAVgADKD1oRksZ0CdRGkkOdJoRHO0EABtUp8OBTMLY+AAXR6RzofHUeAQIwRICotAYTCeOKQpiwpPJTBYbHQnG4lN6UCIcNGiKkF1y+T+SAAykZ9Fo0EY6BAMH1IRIlpkhdSkZcQN5fnMAMIAQTVStEkjJKXhZ1FyL1ylU7KQABVnMr9B7oegrSY/GB+mSIKToNAIl5WAJ9C5YPoWLBNhAsL4MNGAO5YfReCCwaAKbiPMIkaBWzTAYDmohxBL6cuWzLVphpsl0Vx8yuaElB3AAOg7hHr4i75J7g/W1Z6ZDAvKp4mWCsFVxmZM0S0oOMeUCZKFg06YvnKAEdfLAAJKZAS8qQnwi7S9a8S0+iMTfPTSoF/MVjsHkPv8iiZdVRaoMV6FdPCwXVKF0BQmBWNQIA3GkYxyAlvglOYFEgtVrGtYV1UA8cen1ApEHRWdNCw3VcM0AB1bFMhyOIiR6FZj10WBYNAvoBkcRgiSAAAA=&value=N4IgdghgtgpiBcIBSMBOMoE8AEARA9qmCADQgQDmc8ATACxkDG+UsYALgiKSAGYQA3QgEt2MAPrMANoS4BiXvwCsABhU8qYACZouUCFLhkZjCO2H5i8UI1GYuAZQhhsAMVTPbAZ2Y8v7M2oQAGEAQR5bdkx/QMdnNw8wb2YSbDCQAF8yAAcYdi8EAG1QKNyuLXwKHkhYLgB1AzFUTIBdDKAA&theme=bootstrap3&iconlib=fontawesome4), which adds `"required": ["comment"]` to the object after defining the properties, but that doesn't seem to work. Any guidance would be most appreciated. Thanks!

**Comment by gnom7** [comment]
Hello, @jdorn
> I want to spend some time thinking about the best way to handle the asterisks before implementing that.

Has it been implemented?

**Comment by schmunk42** [comment]
@gnom7 https://github.com/jdorn/json-editor#deprecation-notice

https://github.com/json-editor/json-editor/issues/44

**Comment by gnom7** [comment]
Hello, @schmunk42, I assume since you referenced this in json-editor/json-editor#44 we can handle the issue here.
Also I have one somehow related question - according to the README I can specify my own CSS styles, but I cannot find the way to specify CSS classes for elements in json schema (if I could do it, I'd just use `.form-group.required` class from bootstrap to handle the first issue)

> If you want to specify your own styles with CSS, you can use barebones, which includes almost no classes or inline styles.

**Comment by schmunk42** [comment]
I am not too familiar with the code, I'd recommend creating a new issue at https://github.com/json-editor/json-editor/issues

**Comment by germanbisurgi** [comment]
The documentation says you can use custom styles but does not say you can use custom classes. When you using barebones JSON editor it uses almost no classes that can override your styles.

I looked in the source code looking for a feature that does what you want to do but I did not find anything. A solution could be, to extend the theme class and create a new theme for JSON Editor.

You can look in the original repository wiki:

https://github.com/jdorn/json-editor/wiki#theme-srcthemejs

**Comment by gnom7** [comment]
@germanbisurgi, thank you for the suggestion, but it seems that I can't customize form elements this way, only DOM ones (like tables etc.) and it might happen that I'd like to pull one table to the right and another to the left in my form depending on the element which is rendered, or even something more sophisticated, so it would be nice if we had feature to add classes to json form elements, thanks for reply
