### ISSUE TITLE
Ability to inherit and and extend base system?

### ISSUE THREAD

**Issue by patrickcgray** [jdorn/json-editor#165]
I have system let's just call it main_system and one of its properties is called sub_systems and this looks like:

"sub_systems" : {
    "description" : "a list of systems that extend and inherit this system",
    "type" : "array",
    "items" : { "$ref" : "main_system"}
}

So basically it is allowing the user to create a property of the main system that is the exact same thing but a sub system.

I've tried making it "#/main_system" and when I do that it just prints out all the HTML from the page. Then I tried making it /main_system and then creating a /main_system page which is the same schema and it retrieves it but then it just prints it all out and doesn't use it to implement the json-editor. This issue is slightly similar to my previous one (https://github.com/jdorn/json-editor/issues/160) where the definitions were out of order and it just printed out all the HTML. 

Any possible workarounds or solutions?

**Comment by eric-schleicher** [comment]
Following up on this to ask a question.  @jdorn does this mean that it's not currently possible to create an "abstract" animal definition and use that as the base of dog, cat, and bird?   the example being that the the latter three would just extend animal with their unique attributes?
