### ISSUE TITLE
Upload large files

### ISSUE THREAD

**Issue by andrekampert** [jdorn/json-editor#166]
For uploading large files, base64 encoded data in the JSON can be problematic when data.

* exceeds POST limit on server
* needs to be parsed into memory when building JSON AST

I am finishing up an editor that works as follows

* Select file and show preview (based on base64 editor) + upload button
* Hitting upload delegates to upload function defined in JSONEditor config
* Upload function takes (root, file, onSuccess, onError, onProgress)
* During upload, a progress indicator is shown if onProgress is called based on theme
* If upload completes successfully, the URL from the Location header is used as a value
* When rendering existing value, it is possible to download the file

I you're interested, I am happy to provide this functionality and create a pull request.

**Comment by ismaelga** [comment]
shouldn't this be closed?
