### ISSUE TITLE
Start index at 1

### ISSUE THREAD

**Issue by gcerquant** [jdorn/json-editor#167]
When editing an array, the index in the title starts at 0: "item 0", "item 1", "item 2".  
It would be great if the index number can start at 1.

When non tech friendly people use this editor, it confuses them a lot:  

If someone wants to add 10 items to a collection, they start working. Near the end, they are adding item 8, item 9, item 10, and do not realize they have added 11 item to their collections.

**Comment by wmodes** [comment]
How does one use this variable?

**Comment by brettz9** [comment]
@wmodes : See https://github.com/jdorn/json-editor#user-content-dynamic-headers (i.e., use `{{i1}}` within `headerTemplate`).
