### ISSUE TITLE
Redesign Theme and Editor API

### ISSUE THREAD

**Issue by jdorn** [jdorn/json-editor#18]
# Editor

These are methods an editor should implement
-  build() - should build the editor html
-  getDefault()
-  setValue(value) - set the editor's value
-  getValue() - get the editor's cached value
-  refreshValue() - force a refresh of the editor's value by recalculating from the underlying DOM (e.g. get the value of the `<input>` element)
-  destroy() - clean up memory
-  isValid(callback)
-  getChildEditors()
# Themes

These are the methods a theme should implement
-  getFormInputLabel(text)
-  getCheckboxLabel(text)
-  getHeader(text)
-  getCheckbox()
-  getSelectInput(options)
-  getTextareaInput()
-  getRangeInput(min,max,step)
-  getFormInputField(type)
-  afterInputReady(input)
-  getFormControl(label, input, description)
-  getIndentedPanel()
-  getChildEditorHolder()
-  getDescription(text)
-  getCheckboxDescription(text)
-  getFormInputDescription(text)
-  getHeaderButtonHolder()
-  getButtonHolder()
-  getButton(text)
-  setButtonText(button, text)
-  getTable()
-  getTableRow()
-  getTableHead()
-  getTableBody()
-  getTableHeaderCell(),
-  getTableCell()

**Comment by Alanlaosan** [comment]
isValid(callback), Is this method implemented, how to call
