### ISSUE TITLE
Exposure to SCEditor options

### ISSUE THREAD

**Issue by dy2288** [jdorn/json-editor#239]
Hey!

Great work on this wonderful piece of code! I was wondering you have some information on how to use any of the SCEditor options with json-editor?

For example, setting what will appear in the toolbar as specified here:
http://www.sceditor.com/documentation/options/

Thanks!

**Comment by LucianViana** [comment]
Hi, I'm using jsoneditor + sceditor to convert the special characters but when I use "obj = editor.getValue ()" and the contents of the field by "obj.body", but it is not returning the text as it does when clicking the edit button json and display the popup there is some way to bring the same content of the edit json button "by javascript or jquery without the special characters like for example:
  commas, commas, keys are accompanied by the backslash so no error occurs when reading json by javascript or jquery.
