### ISSUE TITLE
Enum's title + values

### ISSUE THREAD

**Issue by DJWassink** [jdorn/json-editor#240]
It would be awesome if we could specify enum's with a title and value attribute. So basically instead of having:

```
enum: [ "value1", "value2"]
```

which aren't saying anything because they are the values, it would be nice if we could specify it like this:

```
enum: [ {"title": "Foo", "value": "value1"}, {"title": "Bar", "value": "value2"} ]
```

This way you will get a dropdown or another element where you will see Foo and Bar as selectables but their values underwater would be value1 and value2

**Comment by leeorengel** [comment]
While #340 is still in flight, here's a non-perfect work-around i've used a few times:

http://jeremydorn.com/json-editor/?schema=N4IgLgngDgpiBcICGAnFSIgDQgGYHsUBbJMBEAZxgBsYBjMnAVwDsBLARyZgEkwYiFBGBTccbfoISgAJChi5yAYgD0AEwVt2YNvhYUVEgQHkoOvUIC+ODbi0Td+6SCNFT5p/FCRY5LfwBzGBRsEBgWJiIEAG0ARiwAJgBdHHwzRyEvMIiiAH0dMFpM6JAANyRqbljQ8sqYBJAky2bLIAAA==&value=NoRgukAA&theme=bootstrap3&iconlib=foundation3&object_layout=normal&show_errors=interaction&no_additional_properties&disable_edit_json&disable_collapse&disable_properties&disable_array_reorder

It just uses a $ref like this:

```
{
  "type": "array",
  "format": "select",
  "uniqueItems": true,
  "items": {
    "$ref": "#/definitions/itemOptions"
  },
  "definitions": {
    "itemOptions": {
      "type": "integer",
      "enum": [
        1,
        2
      ],
      "options": {
        "enum_titles": [
          "value1",
          "value2"
        ]
      }
    }
  }
}
```

**Comment by joseaio** [comment]
After view your  workaround, not show a single select2 (allowing multiple selections)...
