### ISSUE TITLE
Pre-defining external refs

### ISSUE THREAD

**Issue by rarumberger** [jdorn/json-editor#281]
I need to pre-define external refs, as the documentation says I should be able to. Unfortunately, the documentation doesn't actually say how to do it, and I can't make heads or tails of the code - I'm unable to pinpoint exactly what the "refs" option is supposed to contain, and how that relates to "$ref" properties in the schema, or how the JSON editor uses it, or if it even does at all.

For example, I have a schema "http://some-domain/Schema1.json":

```
{
  "type": "object"
  "properties": {
    "a": {...},
    "b": {...}
  }
}
```

I tried to reference it when I initialize the JSONEditor on "http://my-domain/":

```
new JSONEditor(element, {
  "schema": {
    "$ref": "http://some-domain/Schema1.json"
  }
});
```

That gives an error, because the url is not on the same domain (as mentioned in the doc). How do I accomplish this? What should I be putting in the "refs" option, and how do I reference that in the schema?

**Comment by apena415** [comment]
I am just curious. If you have to pre-define the schema, why bother referencing it from a remote location? What is gained?

**Comment by eric-schleicher** [comment]
Nothing apart from segregation.  If its a separate asset, it can be changed
independently
