### ISSUE TITLE
"additionalProperties" : {schema definition} not managed correctly in the editor

### ISSUE THREAD

**Issue by xarques** [jdorn/json-editor#285]
As specified in JSON schema draft 4, section 8.3 (http://json-schema.org/latest/json-schema-validation.html#anchor134), additionalProperties can contain a schema.
If a property name do not match any _properties_ or _patternProperties_, then this property should match the schema defined in _additionalProperties_

The following schema
```javascript
{
  "type": "object",
  "additionalProperties": {
    "type": "object",
    "properties": {
      "state": {
         "type":"string"
      }
    }
  }
}
````
should propose the "string" editor for any new property added. Instead the default editor is displayed:

![image](https://cloud.githubusercontent.com/assets/9682473/5000553/291f4cf6-69ed-11e4-8f3f-f749d2873cc4.png)

Proposed fix: Modify getPropertySchema in object.js. 

```javascript
  getPropertySchema: function(key) {
    // Schema declared directly in properties
    var schema = this.schema.properties[key] || {};
    schema = $extend({},schema);
    var matchPatternProperties = false;

    // Any matching patternProperties should be merged in
    if(this.schema.patternProperties) {
      for(var i in this.schema.patternProperties) {
        if(!this.schema.patternProperties.hasOwnProperty(i)) continue;
        var regex = new RegExp(i);
        if(regex.test(key)) {
		  matchPatternProperties = true;
          schema.allOf = schema.allOf || [];
          schema.allOf.push(this.schema.patternProperties[i]);
        }
      }
    }
	// No patternProperties is defined or no pattern matches
	if (matchPatternProperties === false && typeof this.schema.additionalProperties === "object" && this.schema.additionalProperties !== null) {
          // The additionalProperties contains a schema
          schema.allOf = schema.allOf || [];
          schema.allOf.push(this.schema.additionalProperties);
	}

    return schema;
  }
```
The "string" editor is now displayed:
![image](https://cloud.githubusercontent.com/assets/9682473/5000676/520d84b0-69ee-11e4-87dd-ed8547927a94.png)

**Comment by tmikaeld** [comment]
Is this change considered? It's the exact thing i asked for it in #383
