### ISSUE TITLE
Is there a way to disable editor caching on arrays?

### ISSUE THREAD

**Issue by rarumberger** [jdorn/json-editor#292]
This is not documented behaviour, so I'm not entirely sure if it's a feature or a bug. If it's a feature, I'm not sure why - it really only complicates and confuses the experience for the user. 

If I remove an item from an array and then add a new one, I would expect the behaviour to be that a new, empty/default editor appears. Instead, the deleted editor simply reappears just as it was. In the very simplest cases, this is probably not really a problem, but if the object editor is extremely complex, with multiple objects/arrays of its own, it can be incredibly frustrating and annoying.

Is there an easy way to disable/remove/fix this behaviour?

**Comment by rmeshksar** [comment]
+1

**Comment by wmodes** [comment]
+1

**Comment by leosamu** [comment]
+1

**Comment by arturaugusto** [comment]
+1

**Comment by wmodes** [comment]
Does anyone have a workaround?

**Comment by leeorengel** [comment]
+1

**Comment by stevage** [comment]
+1 from me as well. This behaviour is basically extremely broken for arrays of objects. The only workaround for the user is to create new items before deleting old ones.
