### ISSUE TITLE
Reset the form when switching between "oneOf" schemas.

### ISSUE THREAD

**Issue by jurekpawlikowski** [jdorn/json-editor#293]
When I switch between schemas, properties from the first one are visible in the second which is not a desirable behavior.

### Example:
Considering that I have following schema:

    {
        "title": "Some schema",
        "description": "Some description",
        "type": "object",
        "definitions": {
            "first": {
                "properties": {
                    "prop1": {
                        "type": "string"
                    }
                },
                "title": "First schema"
            },
            "second": {
                "properties": {
                    "prop2": {
                        "type": "string"
                    }
                },
                "title": "Second schema"
            }
        },
        "oneOf": [
            {
                "$ref": "#/definitions/first"
            },
            {
                "$ref": "#/definitions/second"
            }
        ]
    }

When I use the select box to change from the `first` to the `second` schema I expect to get a form with field `prop2` but not the `prop1`. However the result is form with both fields.

**Comment by jdorn** [comment]
I just added a new option `keep_oneof_values`.  It defaults to `true` to keep the current behavior, but you can set it to `false` to do what you want.

Set globally:
```js
JSONEditor.defaults.options.keep_oneof_values = false;
```

Set per JSONEditor instance:
```js
var editor = new JSONEditor(el, {
  schema: {...},
  keep_oneof_values: false
});
```

Set for a single oneOf instance:
```json
{
  "options": {
    "keep_oneof_values": false
  },
  "oneOf": []
}
```

**Comment by falkolab** [comment]
update readme please

**Comment by mbrodala** [comment]
As soon as the `keep_oneof_values` option is documented, this can be closed.

**Comment by drzax** [comment]
This should be closed.
