### ISSUE TITLE
Array in 'items' field

### ISSUE THREAD

**Issue by tusharsoni** [jdorn/json-editor#294]
[JSON Schema core says that](http://json-schema.org/latest/json-schema-validation.html#anchor37)

> The value of "items" MUST be either an object or an array. If it is an object, this object MUST be a valid JSON Schema. If it is an array, items of this array MUST be objects, and each of these objects MUST be a valid JSON Schema.

Currently, only the first object in the array is recognized.

**Comment by trollfred** [comment]
I wonder if someone already implemented it

**Comment by schmunk42** [comment]
https://github.com/jdorn/json-editor#deprecation-notice
