### ISSUE TITLE
Feature Request: Undo

### ISSUE THREAD

**Issue by Z3roCoder** [jdorn/json-editor#326]
It would be amazing to have an "Undo"-Feature. It would make editing much easier. Like, when someone accidentally deletes a value/an entry in an array, it would be very helpful to be able to undo that easily.

**Comment by jdorn** [comment]
You can pretty easily do this on a global level:

```js
var undo = [];
editor.on('change',function() {
  undo.push(editor.getValue());
});
document.getElementById('undo_button').addEventListener('click',function() {
  editor.setValue(undo.pop());
});
```

**Comment by Z3roCoder** [comment]
Assuming an array called undo and a button with the ID undo_button are existent
