### ISSUE TITLE
Property "length" in Object results in Errors

### ISSUE THREAD

**Issue by Z3roCoder** [jdorn/json-editor#328]
Having the array
    {
    "_attachments": {
        "title": "Attachments",
        "type": "array",
        "items": {
            "title": "Attachment",
            "type": "object",
            "properties": {
                "length": {
                    "type": "string"
                }
            }
        }
    }
    }

Results in several Errors that very from browser to browser. 

TypeError: this.input is undefined jsoneditor.min.js.php:7
TypeError: a is undefined jsoneditor.min.js.php:10

**Comment by jdorn** [comment]
Thanks for catching this. It's fixed now. I'm surprised someone didn't run into this problem earlier.

**Comment by Z3roCoder** [comment]
I am surprised by that as well. But since it is solved now it shouldnt be a problem anymore
