### ISSUE TITLE
Custom title

### ISSUE THREAD

**Issue by Ferossgp** [jdorn/json-editor#329]
Hi,
It's possible to add custom title?
Something like this::   title: { type: "string" }

Thank you.

**Comment by Z3roCoder** [comment]
If you mean that you want to give a Property a custom title, that is possible.

"value": {
   "type": "string",
   "title": "CustomTitle"
}

**Comment by Ferossgp** [comment]
This is my code:
http://snag.gy/hvi7P.jpg

This is visual:
http://static.md/831072b75d8c307344c41096886e485a.png

it's posible?
