### ISSUE TITLE
Multiple JSON Editors in different on the same page

### ISSUE THREAD

**Issue by Z3roCoder** [jdorn/json-editor#333]
Would it be possible that perhaps, like in Notepad++ the editor would get tabs? So that you can open multiple files at once and can just tab through all the files? Such a feature would actually be awesome, but it is not possible atm

**Comment by jdorn** [comment]
JSON Editor is about rendering an editor for a single schema.  A UI for switching between different JSON Editor instances is out of the scope of this project.
