### ISSUE TITLE
Leading Zeros are Trimmed

### ISSUE THREAD

**Issue by herrshuster** [jdorn/json-editor#336]
I want to use this editor as part of an application which uses FIP codes. The important part is that these codes often start with a zero which is trimmed when used in a template like {{state}}{{county}}{{place}}

How can I ensure leading zeroes are not trimmed?

**Comment by jdorn** [comment]
I'm not sure exactly what you mean.  Do you have an example schema?  Make sure you're using type "string" instead of "number" or "integer" if you care about leading zeros.

**Comment by herrshuster** [comment]
Yeah, changing it to strings does the job for me.
