### ISSUE TITLE
Nested ref definition 

### ISSUE THREAD

**Issue by Mattes1000** [jdorn/json-editor#349]
When I reference a definition like
```javascript
"$ref" : "#/definitions/systemCommand"
```
and my definition looks like this
```javascript
"definitions" : {

		"systemCommand" : {
			"title" : "System Command",
			"type" : "object",
			"properties" : {
				"systemCommand" : {
					"type" : "string"
				},
				"anywayOnServiceError" : {
					"type" : "boolean"
				}
			}
		}

	}
```
everything is fine!
But when I try to reference a definition like this
```javascript
"$ref" : "#/definitions/jobplansteps/systemCommand"
```
and my definition object looks like
```javascript
"definitions" : {
		"jobplansteps" : {
			"systemCommand" : {
				"title" : "System Command",
				"type" : "object",
				"properties" : {
					"systemCommand" : {
						"type" : "string"
					},
					"anywayOnServiceError" : {
						"type" : "boolean"
					}
				}
			}
		}
	}
```
it doesn´t find the definition!
On [Understanding JSON Schema](http://spacetelescope.github.io/understanding-json-schema/structuring.html) I found

> The pound symbol (#) refers to the current document, and then the slash (/) separated keys thereafter just traverse the keys in the objects in the document. Therefore, in our example "#/definitions/address" means:

>    go to the root of the document
>    find the value of the key "definitions"
>    within that object, find the value of the key "address"

So. Is this behavior "normal"?

**Comment by Z3roCoder** [comment]
Correct way to display property "SystemCommand" of "jobplansteps" here:
http://jeremydorn.com/json-editor/?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIAJGrAGaIgDEA9ACYcIOKBFwZe1KiWgBDHBjCwSGJoPbDR4xKCmUZ8xctUJQYUuRBVaDJiTRYyaSLBOgMRIwFsAwli9e8vw64FBwXADKnkpeAAR+AUFM5mRc1vSMhPaO6C5uIB7eCYE4wabEqUiKaMIA5iAAvoTyRADuskQA8jgR6ABuEHSwAKJoDmghKZaUWFhw8o0NS8tAA==&value=N4IgzgnmAuCmC2BhA9veBDAdgExALlEhgRTS1zxBABoQsIB3dCAeUwGVYAnANwEsAxrACiXLsi74AZugA2YWAF9FQAA=&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by Z3roCoder** [comment]
Also to explain your problem: "jobplansteps" is the "key" in this Example, but "systemCommand" is a property of the key "jobplansteps". You can't reference to properties as far as I know, only to whole keys

**Comment by Mattes1000** [comment]
Of course :+1: I have to think more Schema-Style 
Thanks!
