### ISSUE TITLE
Request: "Format": "checkbox" for boolean type

### ISSUE THREAD

**Issue by wmodes** [jdorn/json-editor#351]
I think this has been sorta requested in issues, but as part of another issue.

It would be swell to be able to specify a checkbox format for bool types, like so:

      "sticky": {
          "id": "sticky",
          "type": "boolean",
          "format": "checkbox",
          "title": "Sticky",
          "description": "Stays visible when page scrolls?",
          "name": "Sticky",
          "default": true
      },

Thanks.

**Comment by Z3roCoder** [comment]
You could take a look at the Custom Editor Interface part of the Editor documentation. You could create your own interface for the format "checkbox" and let it do what it should do. 

If you do so, you could also create a pull request to share your interface with the others who might need it :)

**Comment by jdorn** [comment]
I added this to the latest release 0.7.17

To use:

```json
{
  "type": "boolean",
  "format": "checkbox"
}
```

**Comment by vikash-tiwari** [comment]
Still can't get it work.
Here's my json:

"show":{
              "type": "boolean",
              "format": "checkbox", 
	      "value": "true"
            }
