### ISSUE TITLE
Why does JSON data override JSON schema?

### ISSUE THREAD

**Issue by wmodes** [jdorn/json-editor#356]
I've created JSON data from a schema using json-editor's forms. Later, I've modified the schema, adding a few fields. My expectation was that the new fields would be displayed with null or default data. What surprised me is that the new fields that don't appear in the data are not displayed. 

For instance, in this example, check out the "Video Loop" field in the schema that doesn't appear in the Shot object because it wasn't originally in the JSON data.

[JSON Editor Example with Data](http://jeremydorn.com/json-editor/?schema=N4IglgJiBcIMYAsCGAHALgUwE4gDQjQE8UMYQB7AIwCsM408Cw0AbU2AYWXW0YgwDOcLGHRhyAOzIAVBGAEACeQqQSlEiGABukAK5IWCxKkw58EpAFt28bqcYos5EljRhBMUCiRoEAOV1LSl5oUEgyb18AoN58IhIyMAlMAHNYkEsksEtAmAAGOOY2MgAFHwQFaOCzEH4hETFJMgBVCTAAR10MBUiKyAUJQOrGC2sI8sqh9P4AMyRdFgZoPIBffF6/K3YwqFgNrcZ4mwE0EQkUxkyJABkMc998wtYbMt9Kg/w64VE3JthN6wKGbkLAKXzKXojA57CYA0hrWwmbBVEI7MjGHhYFE1I6JZIYNI1K7ZXLLJ7FTh2bCTGI1L4NX5SWCtDpdIxU0H9Qa0qFjWAY0w04afDBzBZLVb4AXI6Fo/kcuGHYjHU5JC74K63e4IR5MZ5kLhI0GKkX1H7iJkgOFAkFguSKaU1UY2R3vMYIoR3DyhcC7ECeiQeOLKshILBYJCES5JACSmEsAhgAEZ8Lo2p0MHGMAmYHMWAIMPgkBBNIyDFmc9BTl1yTYAMpwL2J03fRqWgAS2G6Ye6vm6AcECgA7sw5GpwQ6Obzjo3A83wPHEz7wrA8kqErAqLR6Ixi6WLQYSk4XG5vdXC3qKSAG16+IJW4yyDGNNo9AYFAPh6OknblI7p2Qa7rMe2CnkuoADtini+mQkFTDiIawEkqTpDkiyiGwADyMzJhqWQ5JYupuPqsA3oGQrTPeDIWi06Zsp+XLwQBsCflBIpios+QerOGCKsufqQR8BCIf6qrnNGNx3CkDxkpe9Y8W6pAttRfwgCyGYfgpzrMf6CkmrUorzJxsAgB6CDkGg4EwSx5mWeuNhhhGUZ4RIFZLimIBpqymaLrmBgFkWJbMAeLBuTA561mQda2fO9LmqpnZYN2SV2v2MVfuC472uyRo6QIMWMMw2ZWSuIBAcJG4UDQdAMIF+6SIeIGuO4S4RXJUW2XeZptk+L46BA+iGPlFkZWOv6Trl5jQmVDhNWB0HDWgUH8bBtlsRVNjIQSqHihhGDYbhGT4aSBTtaRtkUXSVHxZa6n0RdjE8lNfL+hd62zEZEpmRZHCSJgyTQaVi2/fiAPBpVJxnOqR2SdqRFFPWF0g/9tUGd1j6wAAYmAbDOgo5AzB+nXPYjI3I3cDDfWg0iIXKr0WTTCTgyqUMSVq0k6rJxFXtFI2M0paMPjRsAAOrIGgYLKvjhM6AIg0KBgbDWMkSiKBOAD8CgANonDjLC4Ao/UYOQAC6jB3KSWuiXrjBG+QIAmyTq18yGCJ29c5DOIDfru57KD2bBYnQ5qUkyad3M2B7zgKAAFAAapAxsKJhEgsIQACUXVC6pUcoPjoIoCwkYYBA+MSI26s6Qn/DkAoufm9yMBW5IjaMCwfsOx6aBhtTIgpIS3uBz30h9wPzNkNywpnde3euAoI9gP31Lx4ntcp2nmfKTdZAAEqKz42i9rXJw99LRMjTHI4SCylkAHQKHkAC8J+uAbeS3wArI/yAsDM98cKoBQwQBgEgPloDAm8QDaRYrPCWC8l5XQ4l9T4ugIwYzpgNNBNFx6wEnukCOZAAAiqCD6SFjtXJO68M5ZxUpaYhWCyEE3PhLS+SQb4CHvu/L+P8ZgGwAEyPzQEOY+wgMB3AEJA6BIB6GkKkC5EkhFZIfXFMmBEpxVACGCpIfmg9YDqIkJoxkOicGiVZi5dmYdIqwBHhorRahjGC1oWQMWPhJYkDPvowxFpVbjU1lrOAug0AGzmPwYJRckoGxQLofKBsRwkANgEoJPRVAGwEIXZgwTyABIEAbVQ2QfACwtooq2UT8qMESYwEJAsZjhIFnEgWFT1iqEYGklgzBKlZOibuNolgCkOydnoiMBi7Hz1dkWXQmhyAAFElYUxKn6eYkyZnZjmQHWAjlIwSTClzBGZAACCEzxAKGWcrOyW8erWIQN2Q5tdFYrOSGrcWKgUCF0IGCWuE4cqYlvjpRZRyTmrPwEVSsdNyq4k3NVHcViQAHMmcc2ZYNHHb1gHstQSRND9Xln825CKJbAlBJ8x0PyBkzWAs4UCLVoLYvJgDFa6ybk0tRuC0xapDi7JRTchQjKaHIpANjXGWwz7YqBDjAWUjhXcoRNinRdKQDSpDCYyGrLzGh05uHdlMLOUOLihckAud849CLoQEuZcK6/K1QqkARSm4UHLgLduXsTZd2HqPVE1lRIusXmPDaE8mLQrrLA+erqrro2FiAPeRc3DgPeR+QNTDFqxyvuwzhz9YFv0/t/Awf8uWAOAYGFIYCIF5UDfA71yjjKSlqCQ9B7rMGyLWVAv108ZGPnORjaR1bvHxouqw6+bQ74PwzTw/hgjhGaSSuIyR00W3YJhgo3U5alhJjduQFggRtjuq0Ku9dDa8FEiQAAD3ndADyxICLwxIiAOO26xhtrDdetdgImGfOFXc052s8gAFokxmxJS/CWD6d3sU+qohESVOhgCSrsK21K/oU13Dchx/7S3TE7U0fAW7H2kCdW7eQg0AUPN0SAWW+HcXzmZRs5yMNtnqsvQnOW74CNnKRbqvZLBDDPquYbPD7431zLtK41AryY2fMWvfW4SBo2UCLhIAA1jGvcAxa57jsbxsjxKoHTRI4xsjhVfKyrBSJLcNU2V0Z44YJjPLWNor6m+Qw2nDB8ZVr4VxvTZODl0HnPszCdLlUcOS5q3pQAOe5bKkLcHEXMqVeJFVcMdlmYY4Ybld7VL8ruIK207ZpAAFlrg6Qc1yiLlMMPmZlXTBzDiotBzZqqi9V56Py21ddXVLiJZHDPgVpzEtlAa21rrdjBsEBoEsCwX9VrG7QCtv1lgjAhsjf6Zpl6XXRkJARAAL2fPwA9RGNsaAwNtkxe7TNXgAFqfs2/tqz7bCEYHQBUNg4DDCfp6OQRQe7FCWHING/FQ4wwQANvmhQn2pNIDgLJnSZ2LsHYMkgriUoBACAAEJIALERuACPkeo8VdV6F6PFCY4Fjq9tBOjAI7PstmO+KXteMkKksAa3CyaQMIz5woPmCEANhgNAcBb5TpenjhQBO7yw5MmooZNODFEc8XY8jIlKNbP07Rq8NjhmMlis19tKuJeKCp58inEmpMyfk2gWuwPugjjeItPnNhpdq708VIjhnKrGahdPLXdirthvd2Q3X2VOu4t87NAL80fS24tGV91YftGWqq2YmGFi1XQvd4yFbhONdhta247oz7xcjJ6/aSu+BrWTZAKUnUUpAmVOLNU2pjB6nlMr00uR/p0mo2BNk7p+TMALakVH+xYyPWuBQzgWVyHg27qbQQ0iJbx8pctBGwtMb/1nwTb25ND9U093TdwrN/9c3dHzYW63Q857D+FyB5YCI601tKtf2dzKjvQpnehlj120NqBz7YlPa/+0cMHTv3+EdIRERCdAxY/WAZ/ZvM9E6YDFRE9BEPHANHuNHBHJA1wBtaLaGKfeAMnNA1GInMNPA0nRQJhCnKnFAV7OxOnBnVJOAZnA2VnOAdnTnbnXnHSAXPA8/OAkAUyeHAQKZDQFA/gwQ7HOPbAgXAQqAOfMgSQ4g8nXFWOcgygxkagxnIQeg/GbwJgogFgnncAnAxQSQrg4yHglYMDDACDKDG1PvJDWBM/FBBhZvf9AADRKGUNnX/QAE03CJdO5zDLCS4bVwtQZUYKtLVdsts/CzD8BwNdBINAiS9Fp1pgYisWlbJKtc8jEQwcN/C4irDEieJkjCiDgciYiLC8iEiSlyh1p9hb1ERMR1pHRFQnUgAA&value=N4IgDghgLgFgcgVwLYCMCmAnEAuAjABgBpxp4Ik0cQA1AewE8IBzNAAloDNXY2ARWqPRDEAxjAhgomRKkw4ATERBiJUjHHKVsIADIBLDm1oA7bjDYBlcccEpa0YSADOItMbROcAbVAu3aGXQsPCU/dw0KKgBhWiQOWgwoRycYAU9sH2dUqEC5bABWYhSBGJs3JO0wAhFFJwJjfHyAWhSIG3o7aBaEY2N6JoB3PWMAE1oBpoAbWlowADokMAAWZOyAFXowLRAANz0RtFpHKAw2pz0oPRMNraowBBTHCAQRq4BRSbQKG3TM59faKUpDY7tVavVGoMPFCmuIRk0IJNJk0eE0RLF4oknAswABmJ4vK43bYmVzJKAQRJrDB6JgsYJKEYIU6XEw4AjEHa0SbILS4AC+hFA/yuQPKoPwNXwdXwDWaTiQiORAwgO2hkwkYGGTBx+OIItoxKo01m5MpUGptPpOEZzOgV2MOFxSi5PMieH5AF1OXonAhER8vuVfqA9n7EWKQZUwdKIc1JgY0E0TCjzC1rLZ7FAURdPnMAFZgJiOMP+yZG7ROS5IxwALwAkqM0AAPdmiJxOABCECc22Op2M51Zg+8oBOZwuDorIDaekVUjNVJpdLy+DmhRATJZDvZXuIGDQAEcEHoDyMcMYEEivYLfNlcsFcBvilBIxVwDGZcYn+m2pmuhwGCxAidhqoMsIQLWaCTAWRarAI05VnoNbEOOg6TtcmzbPcjz6oStCBt8UC/N6uy+mWhHBt4nq3lkAgPgooTZG+EpSl+ihNGMgiDMMYwDNihbFkU6xYVQSEoSAaFDlOomVA8MAEgClE/NRPrhpMynEdRtEvgx2DyM+zEmMC75VJK4KygZnECP0TBKmg9CwUJdEWrJzjVpM/YTsO044QpeFKZ8REkWpFFBVRGQ0UKLl6c6wklMZ4rRuZsays61ncQMCQANYUigeaCfBrm3JWHleehPluX5invOFKmRaFAZ1VpkU6feyBBE6hkJWUUYfilX64s0XH9NMHBQE5RWIWVqEDtJmEleA8k1QRzUhWR6maSRbX0R1eRLExPUmaxFnGAdGX9IYGDGJN8XFds4mebN3kyYt1UBbVQb1V4pGlk1X0tT9O05HtwRLN1r6JX1ZlsfU4MXVMegoKcGCOYVd3TchT2SXNGHGL5y0fatAPrX9Glrdp0W6aDOD5IdkO9aZn71HTCPmBAIy3S5mMSVJeME7hM74VtqkbWFJOU3eu2yMEABs9MsclsOyvLCM9AcGBNMj+wsFzL489jfOVW9hNC4FEsNWL/3BdpUW+K44Q0/poQOwEmhUAAsg8egiEVIYxU7EOK/1bGKHKaLTL2CBgMmHBNKcAJ6yJi2PeV8341VpsGiLGTCvhwcw7UYeQnYKA8UiTgtBS/QQIjUBQJ8UwmPSuordOJpgIuFrLta2BNPI67EFu9pstgSyD7s3K8ja660QaBefsXzQJ1cWttPCUA9NqrdE+3Myd0UFJLlaeT93MSxD3aw4z7gnJT+6a75HP+dQ0zA1L/HHOryg68olvxg6kWHqM2RI3Idy7paFcwR5CX23KPNct9J5ui0I/Z+AIF7v1lJCAY0IkDexEIMHsTQ5xgASBSGwO8QGGjcqSSgh9zSQN7o/WBI9HR4Anq6aeHpfrkWthFIGVN2oy3ZArV+J1pRhwIBHWgUcY6cDXsYfMtAk4ITcqnZ6FVXrYSzsLCmlsyY5yBnbZwrtYou38BEbYbxjx6DAERP2o4A7CIKHdDBbFnThweEwSuiowACTghjNRM0cYvQWtowW2c9F/BfozcRTgPHYOhDgiC8InAQEMNxI8J47HlEoQaactCIE91XBPYe18XFIK4QKHhm0onGOps4jkLk3G1A8VIhMhgmhqirP45y+sglYzTvzTOETdEWx+o1cm4z6lCM6ngIOYilatNlD+DpSYaQAJUfdMSwSjZaLuDo82Nt9G8KmccgRUsQbOMUK4xZIdlnGA4oqDZ6yv7KPRtzAZvNcbG3Cf5Khhiani3OTM6WcyDK3NiUs6UHirJtDEAkXpU0vmGx+fsuSoyjn8KBXw76oKrngoAOyQuOtC+JllCU5jAGAfoqIRBtFoGgLZBshm/IOZiz6ILJmAuBmYklSV7kwrSvgJoSBNZKJgIOFMwwmhgA1K4ZlKLWXoqWhy4mXKrZnOxbyp2Q1+XQ0/B4oaorxW0ElU4FMrw0kdi+PlNAnMPn9JTrstFYT2X/MidM7ldSbxU1MU7A6RRTHu20AAMRmOeO6/sGlzIWVCwVTgDrhx/uiYwTRAL0G3osFYgTFp7AOEcDR6cBYerGecvO6C7ltxocYMk9Dj5QJtCw8piDOHumqd66ZOrnGiPjci51gyfQFp0PvKghT63dxPgyZtO48BFuGSbNVgLO0gpvDRIAAAA==&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&show_errors=interaction&required_by_default)

Is this expected behavior? Is there a workaround for this? Is there a way the form can amend the incoming data?

**Comment by Mattes1000** [comment]
Your example URL doesn´t work. The URL is 'invalid' 

Did you check the "properties" button? Are the fields you are missing listed there? If so, check the Parameter "required" for theses fields.

**Comment by wmodes** [comment]
The URL is goes directly to jdorn's json-editor example which allows you to input schema and generate a form and then with the form generate JSON data. Or from JSON data you can have it populate the form. 

I was using the form on my own site tonight and happily it doesn't do what I reported the example did. If the data doesn't contain fields in the schema/form it just assigns them the defaults. In fact, if the data contains fields not in the form, it adds new fields to the form.

So we can consider this resolved.

**Comment by Mattes1000** [comment]
Hm, maybe it´s a problem with one of the proxies I´m behind. The URL maybe to long for one of them ;)

**Comment by Z3roCoder** [comment]
You need to add "required"-Fields if you want to force property fields that are not in JSON Data.
