### ISSUE TITLE
How to tell which field is being watched or its modified value?

### ISSUE THREAD

**Issue by wmodes** [jdorn/json-editor#357]
I love that I can use editor.on('change'...) to automatically save after each field modification. But I don't want to save the entire object after each change. So how can I find out what field was modified?

I've tried the following hoping some info was returned with the callback.

    jsonEditor.on('change', function(e){
        console.log(e);
    });

No dice.  Suggestions?

**Comment by wmodes** [comment]
A related problem is that with the listener, the function is triggered before the value is available through the editor object.

    jsonEditor.watch('root.pathNumber',function(e) {
        console.log("pathNumber changed");
        checkRecordChange(e);
    });

    function checkRecordChange(e) {
        var myChapter = jsonEditor.getValue();
        console.log("returned: "+e);
        console.log(myChapter);
        console.log("pathNum: "+myChapter.pathNumber);
    }

But my object from json-editor doesn't yet contain the watched field. Nor does watch function return any values.

Useful if it returned an index to the changed field and the newly changed value of the field.

Am I missing something?

**Comment by jdorn** [comment]
The watch callback fires immediately before the change has a chance to bubble up to the root. This might do what you want:

```js
// Get a reference to the node within the editor
var node = jsonEditor.getEditor('root.pathNumber');

// Watch the node for changes
jsonEditor.watch(node.path, function() {
  // Get the value directly from the node you're watching instead of the entire editor
  console.log(node.getValue());
});
```

**Comment by wmodes** [comment]
Thanks.  That helped.
