### ISSUE TITLE
Local references to array definitions are not shown as arrays in the editor

### ISSUE THREAD

**Issue by andig** [jdorn/json-editor#371]
When array definitions are referenced from properties, they show as objects where the type needs to be selected first instead of as arrays. See this example:

	{
	  "title": "Person",
	  "type": "object",

	  "definitions": {
	      "pets": {
	      "type": "array",
	      "title": "Pets",
	      "items": {
	        "type": "object",
	        "title": "Pet",
	        "properties": {
	          "type": {
	            "type": "string",
	            "enum": [
	              "cat",
	              "dog",
	              "bird",
	              "reptile",
	              "other"
	            ],
	            "default": "dog"
	          },
	          "name": {
	            "type": "string"
	          }
	        }
	      }
	    }
	  },

	  "properties": {
	    "pets": {
	      "ref": "#/definitions/pets"
	    }
	  }
	}

**Comment by jdorn** [comment]
You need to use `$ref` (notice the dollar sign) instead of just `ref`.

**Comment by andig** [comment]
doh: I'm feeling stupid, thank you!
