### ISSUE TITLE
Selectize Support

### ISSUE THREAD

**Issue by philostler** [jdorn/json-editor#386]
Myself and a colleague are currently working on integrating json-editor into an application with many complex views being driven off the output of the JSON schema.

The decision to use Selectize instead of Select2 was made a long time ago in this project and thus we're looking into supporting Selectize in json-editor, beginning with the `select` and `array` types.

Here is a screenshot of our work in progress (obviously this is in development, the `array` type is side-by-side with the originial for comparison).

![selectize 10 34 37](https://cloud.githubusercontent.com/assets/244198/7470185/9b3fd932-f312-11e4-96c9-2f04871b6c67.png)

Would there be an interest in a pull request to add Selectize support back into master? I prefer if we would (1) contribute back and (2) side step the need for us to maintain a forked version just for Selectize support.

Thoughts?

**Comment by jdorn** [comment]
Yeah, I would definitely be interested in a pull request.  An array tag editor would be awesome.

**Comment by philostler** [comment]
Great! We've actually got a fully working version now with Selectize support for the `select` and `array` types. We just need to clean up the code a little before starting a PR.

Now there is the option of being able to use Select2 or Selectize, how would you prefer that choice be made? In our version, @radioisradio has introduced a boolean flag to decide whether to use Selectize whereas I am taking the approach of priority, Select2 first, then look for Selectize etc... Thoughts?

**Comment by philostler** [comment]
Closing as Pull Request is now open for Selectize suport #399
