### ISSUE TITLE
Foundation Vertical Tabs

### ISSUE THREAD

**Issue by shannoncruey** [jdorn/json-editor#401]
In line 6404 in the 'getTabHolder' function, the second div with the 'tabs-content' class should also have the 'vertical' class.  Vertical tabs in Foundation require both the tabs as well as the content panel to both have the 'vertical' class.

Tweaking the code fixed my presentation issue, but not worth the full round trip of a fix and pull request.  

Thanks!

**Comment by stevage** [comment]
Ah...wish I'd found this. Gave up on using Foundation as it looked like a complete mess...
