### ISSUE TITLE
array of arbitrary string is not supported?

### ISSUE THREAD

**Issue by rain1017** [jdorn/json-editor#478]
{
	'type' : 'array',
	'items' : {
	      'type' : 'string',
	},
},

**Comment by mbrodala** [comment]
[Works fairly well](http://jeremydorn.com/json-editor/?schema=N4IgLgngDgpiBcICGAnFSIgDQgJZhgFsBnBUSWBEYsFXAOwHMQBfFoAA&value=NoXSAA==&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction) if you fix the JSON syntax errors.

**Comment by rain1017** [comment]
Fixed, it only happen when I put it inside an array and set format as 'tabs'
