### ISSUE TITLE
grid_columns doesn't work

### ISSUE THREAD

**Issue by yi-ji** [jdorn/json-editor#483]
my json is : 

```
{
    object_layout: "grid",
    schema: {
        type: "object",
        title: "Global Settings",
        properties: global_settings,
        options: {
            collapsed: true,
            grid_columns: 2
        }
    },
    theme: "bootstrap3",
    iconlib: "bootstrap3",
    no_additional_properties: true,
    disable_properties: true,
    disable_edit_json: true,
    disable_collapse: false
}

the variable "global_settings" is as following:
{
"Region": {
                "type": "string",
                "enum": [
                    "NY",
                    "LN",
                    "HK",
                    "TK"
                ],
                "default": "NY"
            },
            "Env": {
                "type": "string",
                "enum": [
                    "QA",
                    "Prod",
                    "Dev"
                ],
                "default": "QA"
            },
            "Logback Level": {
                "type": "string",
                "enum": [
                    "ERROR",
                    "DEBUG",
                    "WARN",
                    "INFO",
                    "TRACE"
                ]
            }
```

The problems is "grid_columns" seems has been ignored. I have tried to put it elsewhere (inside the properties or outside the schema) but neither works.

Please help. Thanks!!

**Comment by sschatts** [comment]
Make sure you have the bootstrap link in your html: <link rel='stylesheet' href='//cdn.jsdelivr.net/foundation/5.0.2/css/foundation.min.css'>

And then the answers in this issue will help you: https://github.com/jdorn/json-editor/issues/358

**Comment by privanick** [comment]
@sschatts do you mean to say that certain style features (like grid layout) do not work in basic html mode. I am running from a deep embedded server and wont always be internet connected and I want to avoid all external dependancies like CSS frameworks. Although I could add a minimal set CCS definitions if I new what was required to make things work.

**Comment by privanick** [comment]
I have now loaded bootstrap3 style sheets and theme and the grid layout for an object now works
