### ISSUE TITLE
Remove Type Dropdown in Form

### ISSUE THREAD

**Issue by kwkevinlin** [jdorn/json-editor#492]
I have a schema that has certain values that look like this:

```javascript
{
   "product": {
      "type": ["string", "null"]
   }
}
```

In the generated form, it shows the types as a dropdown, and if null is selected, the text box is not displayed at all.

![image](https://cloud.githubusercontent.com/assets/7246828/9118634/d49c8bdc-3c3f-11e5-94ae-e8a5c33179f6.png)

With string selected: 

![image](https://cloud.githubusercontent.com/assets/7246828/9118644/e571c512-3c3f-11e5-883c-11dc21726ac9.png)

Is there a way to not display the dropdown at all? In JavaScript, then I can maybe say if input is blank, then set image_url as null.

When we put a starting_value as {} (empty), the form also defaults to "null", which will not show the text box. Is there a way to make the generator show the textbox by default (defaultProperties?)?

As a side question: is there a way to specify only to show 2 columns when using the "grid" parameter when creating the editor?

**Comment by Papipo** [comment]
You should probably set the type to just "string" and set the value to null if the string is empty at the application level.

For the case where you want a string set, using minLength and format is the way to go.

**Comment by kwkevinlin** [comment]
That was really helpful, thanks! Are there any concise ways to check for empty strings in the JSON Editor, for example after clicking a button? The form itself is quite large unfortunately.
