### ISSUE TITLE
tabs array remove-add bug

### ISSUE THREAD

**Issue by sinanguler** [jdorn/json-editor#504]
json has root properties that name is pets
this property's type is array and format is tabs.
click "remove last pet" 
and add click "add pet" 
new pet object added but it have any propery
if you have clicked to "remove all"
json-editor remember last cleaned headers when click every "add pet"

http://jeremydorn.com/json-editor/?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIJaWZaksGioOAhgFtyoMKXIgMYNBBwBzJgBMudaSUi5EIAGIRMYAAR8cC/QBk+k/fyFMBM07DlgAFogAshJQDM+AV2iMSABS6LACRPoAIlhoeAC+hHyywsRkmjJgsMloirA+/oEATACshHY4EAK+AogAjAAcZXwAHpXViACcHQkgPgBuMVCwAPp0WNAxPKniktJyTF4xAnyBIGMTOYSQMOL9g5n665OeeX4BmgDEXj7FAAy3ID3JxuhTomlIszLyhI7tCABtEDLOALMJ8UEAXR6EzoKwgGgQIjEmiotAYTG2oKQpiwcPUeEILDY6E43CRaygRDeKM+Um+uXy5yQAGUjPotGgjHQIBgxo9CJIVil3jN6fMTkzVgBhACCAspoiFmRpHwk4p+ICUfNUBM0ABVnLz9MbnuhhSY/GAsMtIHDoNAIl5WAJ9C5YPoWLA+gjfBg3QB3LD6LwQWDQBTcLZhEjQYWaYDAHmiOIJfSJ5WwVNMAMrOiuCnJ6lIWHw3AAOiLTEzmlLBPLNdTqaJsDA5ORar4aC51MIizQts0YD4lCj4Cg2JQrbHvgqAEdfLAAJKZATkqSLwhDNeq8Ro+iMLYT8SoQ8gZywPhKND6mNxlVIRP6DDhrzl0X6VP6BDp4DP1/ltYHrZoQAAkaB5JcAD03gyFACI4BgUFkIwTaSnBBLtswra7qiNAHkwbCYVMCi8iOcDDMS7BkogG6wJ4ZGUBR6xxiQL60Wgi49FRpJhlhoq4XScyan8NSAmsKyKFgmqULoChMBBagQKChBYO6OSQpKZyrAo0kKkBgnqsJjxNnEQA&value=N4IgdghgtgpiBcIBSMBOMoE8AEARA9qmCADQgQDmc8ATAKxkBmEAboQJYAuMA+gMb4ANoQQgAxI2Z0ADNNIgqYACZpRUCILhlhfCJ3b5i8UHy6ZRAZQhhsAMVTXTAZwHynnPdRABhAILzTTkx3T0trOwcwZwESbD8QAF8yAAcYTicEAG1QINTRJXwKeUhYURK4JJzMPMQCorJysugYGkSAXQSgA=&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by VincentSJ** [comment]
Some addition:
If we have main element with "type":"array" and then add->remove->add again, json-editor will restore this element as empty.
We can solve this by adding "format":"table/tabs" to main element, but it's not a good idea in case we have more included "type":"array" elements in main element (it will looks unreadable)

Here is an example when we have multiple type=array form and add/remove/add bug:
http://jeremydorn.com/json-editor/?schema=N4IgLglmA2CmIC4QFkCCBJAcgAgCrtwBkBRbAcQHliBlbACWICViQAaEAE1gGcBjAJwgAHSAHsAdohAARHgOFjx2UQDNlAV37ZYcALaxxYbAAtY/eOzABPIfCQBDfv3tW2IKLF3dEoSDDsoGJhu1rZSogBGAFawvGBuQvyitvyQPD4gKqKiGX5wUsj2EEp5FpxygiIQElK6RUrFQupGKhA6HCE2AdxgguIA5iAAvuwRjrlQ+UgACoK8ZVx8lYpSAO460KzYYMb2YADk3NjcELpC+ZZdUo7OruweXhP+UrMQ89ji6roRZp1hSJ9vr8hiCQUAAAA==&value=NoXSAA==&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by tom10271** [comment]
I got the same bug too....

**Comment by arturaugusto** [comment]
Me too. Does anyone has a workaround?

**Comment by tom10271** [comment]
Fall back to use v 0.7.20 does not have this problem. You might try 0.7.21
too but I didn't.

2015-09-04 20:41 GMT+08:00 Artur <notifications@github.com>:

**Comment by ivan4th** [comment]
Preliminary fix: https://github.com/ivan4th/json-editor/commit/869ab3fdc2c4f6077dda44e769bfb936c83dd57d (needs testing)

**Comment by ivan4th** [comment]
Actually this commit caused the bug: https://github.com/jdorn/json-editor/commit/7da25424d2dd40b8c45f3d01af77dc13e78e6b87

**Comment by bastianwegge** [comment]
Is there any chance this is going to hit a release? I'm still getting this error/bug.
