### ISSUE TITLE
Doesn't work with the mother of all JSON Schemas -> JSON Schema Schema

### ISSUE THREAD

**Issue by successhawk** [jdorn/json-editor#507]
Nice tool, but using the interactive demo it doesn't appear to work correctly with the mother of all schemas -> http://json-schema.org/draft-04/schema#
I expected to be able to create a schema using the generated forms.  It loads something, but I'd say it's not even close to being correct, and it doesn't allow me to generate anything.
I had to enable loading external schemas (which I had to debug to see that was necessary). But even then I got the following error (see image).

![image](https://cloud.githubusercontent.com/assets/3745327/9684679/0d9e7b3a-52e7-11e5-98c3-6f25a2e3bc55.png)

BTW, the forms were totally blank when I tried to load the Swagger 2.0 json -> https://raw.githubusercontent.com/swagger-api/swagger-spec/master/schemas/v2.0/schema.json

Update: the latter "swagger" issue looks like it's CORS related, but I would like to know how to get around it if possible.
Error: XMLHttpRequest cannot load http://json-schema.org/draft-04/schema#/properties/title. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://jeremydorn.com' is therefore not allowed access.

**Comment by wengys** [comment]
I think this is a bug relating to "positiveIntegerDefault0".

After some hours debugging, unfortunately no idea how to fix this.

**Comment by jdorn** [comment]
With the most recent update (v0.7.27), both the JSON Schema schema and the Swagger schema should work.

http://json-schema.org/draft-04/schema is really badly written, so the editor it produces is almost unusable.  I added a file `examples/meta_schema.json` that does a similar thing, but gives a much better UI.

As for the CORS issues, nothing I can do about that.  Either host the files locally or fetch them with a back-end script (e.g. PHP) and pass them in with the `refs` option during instantiation.
