### ISSUE TITLE
0 default for integer fields is not ideal

### ISSUE THREAD

**Issue by scott2b** [jdorn/json-editor#519]
This is unexpected behavior for the typical web form. Normally I would expect a numeric field to be empty until filled by the user. The default 0 behavior is inconsistent with the way a text fields behaves (blank until filled) and is particularly problematic (i.e. confusing) when, e.g., a non-zero minimum is specified on the schema.

Is there a way I can get integer fields to default to blank instead of 0? Thank you.

EDIT: the case of a specified minimum is probably best handled with a default value set to the same as the minimum. However, default 0 as generally problematic still stands. There are many cases where a default value doesn't make sense and 0 as the default value is even more confusing. Note: I have tried an empty string and null both as default, but these get coerced to zero in the form generation.

**Comment by cjc343** [comment]
JSON Schema does not allow nulls for number fields.

One possibility is to specify multiple types (per #244) however this doesn't transparently switch between null and numeric types which I found makes it unusable for me.

Personally, I'm more concerned with not using 0 as a default value than with violating the constraints set forth by JSON Schema, so I modified the relevant editor(s) and validator to support null values for number and integer. 5447c0339063d9902e0279e93f17b43aa510ce86

Per the commit message, if those changes don't break things now, they likely will in the future. Any use is  at your own risk.

**Comment by scott2b** [comment]
Sorry, I did not mean to imply that null or blank integers were schematically valid, rather I was merely fishing for a way to trick the form rendering into providing a blank starting value. I am wary of an approach that breaks proper json-schema.

The issue I am having is not really directly schema-related. It is more about form rendering, and particularly in the case of initially rendering a form before the user has provided input.

I admit, I am unsure why you would not simply treat an integer the same way you do a string field, with respect to initially rendering the form. Which is to say only provide a value to the form if there is a default value or if initial form data has been provided. If I create a string property with a minimum length, the form that is rendered is not pre-filled with some arbitrary text string. It is not clear to me why I should expect different behavior for an integer or other numeric field.

**Comment by cjc343** [comment]
>  I did not mean to imply that null or blank integers were schematically valid

Didn't think you were, just explaining why numbers get coerced to 0.

The issue is schema related because it is json-editor's adherence to the schema which causes the initial values for numerical types to be 0.

> I am unsure why you would not simply treat an integer the same way you do a string field, with respect to initially rendering the form

Strings are initialized to empty strings. Empty strings are not numbers and would be a violation of the JSON Schema just like allowing nulls in numerical fields.

The commit I linked shows how you can modify the default handling of a given type. I chose to go with allowing null values for numerical fields, but you may implement any default behaviour you wish.

To be clear, I'm not involved in the development of json-editor or the JSON Schema, just chiming in due to having experienced the same issues with 0 not being an appropriate default value.

**Comment by scott2b** [comment]
Ok, thanks for this. I am starting to see how data initialization and the schema work together. It's a bit unexpected at first -- it is generally expected that a create form will not be valid when initially rendered and as such I'm not sure I would take the same approach, but it seems to maybe be fundamental to the way the library works.

I am currently in evaluation phase, and while some of these particulars of behavior I like better in other libraries (handling of form initialization and handling of required properties), I really like the way json-editor decouples and makes things more cohesive and makes fewer assumptions about the overall working environment.

Thanks for your feedback and input. I will take your code customization ideas to heart -- although I do mostly need a json-schema compatible approach, so I'm not sure yet if this approach will work for me. Thank you for the idea though.
