### ISSUE TITLE
API to hide fields from editor

### ISSUE THREAD

**Issue by pwalsh** [jdorn/json-editor#523]
We did not see an API to hide fields from the editor.

Our use case is that we use JSON Schema to create representations of various data handling specifications we have. And, we also use these schemas to generate forms for data entry. However, "normal" users who would use the web form do not need to see all the possibilities of the spec - it is confusing. So, we want to be able to hide certain fields when using json-editor.

We've added `hideFromFroms` as a boolean to do this. Example:

https://github.com/dataprotocols/schemas/blob/master/data-package.json#L76

Is this generally useful as part of the json-editor API, just like `propertyOrder` and such?

**Comment by TheSustainables** [comment]
We're using the editor option `hidden` to do this. Or is this another usecase?

**Comment by pwalsh** [comment]
That doesn't seem to work for fields.

Example:

https://github.com/dataprotocols/schemas/blob/master/data-package.json#L76

This schema generates the default form on

http://datapackagist.okfnlabs.org

But it still displays "contributors"

**Comment by TheSustainables** [comment]
It needs to be like `options: { "hidden": true }`.

**Comment by pwalsh** [comment]
ah.

Got it. Thanks.
