### ISSUE TITLE
Array Items with the same type

### ISSUE THREAD

**Issue by rolfn** [jdorn/json-editor#532]
I defined in a schema something like the following
```
"foo" : {
  "items": [
    {
      "type": "number"
    }
  ],
  "type": "array"
}
```
The editor knows the type of the first item (number). But for the following items I must choose the type explicitly. I expect that the type definition should be valid for all the array items in this case.

Many thanks for your very good library.

...Rolf

**Comment by sm587** [comment]
Try:
```javascript
"items": {
    "type": "number"
}
```

**Comment by rolfn** [comment]
Oh, my mistake! I haven't understand the standard correctly. Now it works like expected, Many thanks.
