### ISSUE TITLE
Click events are eaten by json-editor when changes occur

### ISSUE THREAD

**Issue by KevinSjoberg** [jdorn/json-editor#539]
I've created a JSFiddle to demonstrate the issue. See https://jsfiddle.net/q4q5ohu4/. I've also created a GIF that reproduce the problem. See http://d.pr/i/1jRwV/4ZWGqfDq.

As you can see the click events are not firing for the submit button since a change occur as you press the submit button. json-editor seem to "eat" the event and stopping further propagation.

**Comment by hovsater** [comment]
I'll assume this issue have been solved by now. If it's not, I'll make sure to reopen it.
