### ISSUE TITLE
If we add an array element through add button, after deleting any of the element in the array, empty object is added instead of adding the object with its properties

### ISSUE THREAD

**Issue by SathyaPrettryCool** [jdorn/json-editor#547]
Schema used : 
{
  "title": "Person",
  "type": "object",
  "properties": {
    "Samples": {
      "type": "array",
      "title": "Pets",
      "items": {
        "type": "object",
        "title": "Pet",
        "properties": {
          "type": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        }
      }
    }
  }
}

In the above schema I have added the array pets. in the json there is no format(table , tabs) specified
When i tap the "Add Pet" in the UI it adds the array element perfectly. if i tap "Add Pet", after deleting one element from the pets array then the empty object is added without having any properties. In the following resulted json we can see the empty object in 3rd and 5th element of the array 

Repro:
1. add three elements by tapping add pet button
2. delete the second one 
3. tap again the add pet button
4. we can see the array element added with empty object that doesnt have any properties
Resulted JSON:
{
  "Samples": [
    {
      "type": "",
      "name": ""
    },
    {
      "type": "",
      "name": ""
    },
    {},
    {
      "type": "",
      "name": ""
    },
    {
      "type": "",
      "name": ""
    },
    {}
  ]
}

The following are the links to the schema for reproducing the issue:

http://jeremydorn.com/json-editor/?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIJaWZaksGioAygIYBbEnG4JQYUuRD80afkSaQY01GG6EosQWIlTEIKrQZKocA2qYs26TruJkeD6RjBoIOAOYgAvoRxC5HqOSK7uXr4+UVFAAA==&value=N4IgyghgtgDgNgUwM4gFwG1QBcCeMFoggA0IAdtAakQL7HZ5VGkVRMh3Cci76EnlK/br3Ysh1DvRoBdGkAA=&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

http://jeremydorn.com/json-editor/?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIJaWZaksGioAygIYBbEnG4JQYUuRD80afkSaQY01GG6EosQWIlTEIKrQZKocA2qYs26TruJkeD6RjBoIOAOYgAvoRxC5HqOSK7uXr4+UVFAAA==&value=N4IgyghgtgDgNgUwM4gFwG1QBcCeMFoggA0IAdtAakQL7HZ5VGkVRMh3Cci76EnlK/br3Ysh1DvRoBdGkAA=&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&disable_properties

**Comment by tonylucas1270** [comment]
I'm seeing exactly the same problem, checking getValue() the array item still has got some data in it (from the template I think), and is identical to a 'correct' new array item, but will not display correctly, and there is no way to fix it apart from create additional items and then delete the broken one(s)

**Comment by tonylucas1270** [comment]
Just to confirm #543 completely fixes this for me

**Comment by SathyaPrettryCool** [comment]
Actually this is creating messy tony. sometimes even the added second element is also empty. We can't ask the user to add as many items until it gets the eleents displayed

**Comment by SathyaPrettryCool** [comment]
#543 is fixed for me as well. #547 is working fine. Thank you for providing the fix..
