### ISSUE TITLE
Upload file option?

### ISSUE THREAD

**Issue by hutch120** [jdorn/json-editor#548]
Hi All,

I've been checking out this framework to generate forms for my website, but I need an "upload file" option (actually takes photos when run on a mobile device), but I can't see where/how this might be  possible, any tips?

Sorry if this was already covered somewhere. I might be keen to add this as a module/plugin if need be.

Thanks in advance.
Simon

**Comment by rabidgadfly** [comment]
Searching issues brings up a couple of options. 

From https://github.com/jdorn/json-editor/issues/472
```
"imgData": {
            "title": "Simpsons Imaginary",
            "type": "string",
            "media": {
                "binaryEncoding": "base64",
                "type": "image/png"
            }
        }
```
From https://github.com/jdorn/json-editor/issues/513
```
"files": {
"type": "string",
"format": "file",
"title": "Files"
}
```

**Comment by hutch120** [comment]
Thanks Glenn! I used the second one. Perfect!
