### ISSUE TITLE
Edit dynamic-length form

### ISSUE THREAD

**Issue by alfredopacino** [jdorn/json-editor#563]
Hi, I'm not clear if I can pre-populate the fields with my data, if so how?

**Comment by gfb107** [comment]
You can, easily. There are 2 way.

1. Set startVal in the editor options when you create your JSONEditor
2. Call setValue on the editor

**Comment by eric-schleicher** [comment]
to be clear, if you wish to set the data initially without maniulating with javascript (e.g defining defaults in the schema) you can use the `"default"` attribute

```json
                    "defaultFontSize":{
                        "title":"Default font size",
                        "type":"number",
                        "description":"large values in conjunction with autosize will result in initiall maximized size within the constrain area",
                        "enum":[10,18,24,28,32,48,64,72,128],
                        "default":64,
                        "propertyOrder":14
```

**Comment by alfredopacino** [comment]
For the current project I used angularjs, but I will definitely use this for another one. thanks
