### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by solsson** [jdorn/json-editor#568]
This is a great component and it works well with Webpack. Please publish the new 0.7.24 to [npm](https://www.npmjs.com/package/json-editor). Thanks.

If you want to I could maintain the npm package.

**Comment by dougmacklin** [comment]
It looks like the version number was updated to 0.7.25 in the package.json, however it was never published to npm (still showing [0.7.23](https://www.npmjs.com/package/json-editor) from 7 months ago). Any chance the new version could be published? Thanks in advance.

**Comment by jdorn** [comment]
Just published the latest version. I'll make sure to add this to my release process going forward. Thanks.

**Comment by solsson** [comment]
@jdorn Please publish 0.7.26 also. Thank you.
