### ISSUE TITLE
setValue on a schema that includes oneOf

### ISSUE THREAD

**Issue by domaindrivendev** [jdorn/json-editor#569]
Hi there

Firstly, thanks for an awesome library! I've been experimenting with it as a solution to a significant problem we have at my company. For us, the value from this kind of tool would be immense. However, there's a couple of wrinkles we'd need to iron out - of course, we'd be more than willing to contribute!

We want to implement complex form branching based on selected values. I've got this working pretty well using the "oneOf" construct. However, we also need to support form editing based on previously submitted JSON. In this case, we would need the form to be initially rendered in the state represented by the JSON passed to "setValue".

One of the challenges is that the current support for "oneOf" doesn't include a discriminator in the JSON output. So, there's no easy way for a consumer of that data (in our case a Rails API) to know which branch was selected. Then, for the same reason, it's also going to be difficult for the editor (which is also a consumer of the JSON) to know which form elements should be displayed on initial render.

So, just wondering if this is something that's come up before and if you have any ideas on how hard it would be to implement?

Cheers

**Comment by gfb107** [comment]
setValue with oneOf will work as long as the value is valid for exactly one of the schemas in the oneOf.
setValue won't work if the value isn't valid against any of the schemas, or if is valid against two or more of the schemas.

Generally you discriminate based on the presence of properties that are unique and required in each schema.  You can also use a common property with different valid values.  You can create an artificial discriminator using a common required hidden property shared by all the schemas, but that has a different valid value in each schema.

```
{
  "oneOf": [{
    "title": "One",
    "type": "object",
    "properties": {
      "discriminator": { "enum": [ "one" ], "options": { "hidden": true }}
    },
    "required": [ "discriminator" ]
  }, {
    "title": "Two",
    "type": "object",
    "properties": {
      "discriminator": { "enum": [ "two" ], "options": { "hidden": true }}
    },
    "required": [ "discriminator" ]
  }]
}
```

**Comment by domaindrivendev** [comment]
@gfb107 - thanks for the info, it helps a lot.

I was hoping you might answer one more question related to oneOf before I close this ticket:

Do you know of an easy way to display an empty value in the oneOf select box - i.e. show none of the fields until a value has been selected? I've been able to do it with the following but it doesn't feel right as the empty option shouldn't be considered a valid schema

    {
      "oneOf": [{
        "title": "Select one ...",
        "type": "object",
        "properties": {
          "discriminator": { "enum": [ "none" ], "options": { "hidden": true }}
        },
        "required": [ "discriminator" ]
      }, {
        "title": "One",
        "type": "object",
        "properties": {
          "discriminator": { "enum": [ "one" ], "options": { "hidden": true }}
        },
        "required": [ "discriminator" ]
      }, {
        "title": "Two",
        "type": "object",
        "properties": {
          "discriminator": { "enum": [ "two" ], "options": { "hidden": true }}
        },
        "required": [ "discriminator" ]
      }]
    `}

**Comment by gfb107** [comment]
Try making the first schema impossible to validate against.  There are a number of ways to do that.
```
{
  "oneOf": [{
    "title": "Select one ...",
    "type": "object",
    "minProperties": 1,
    "additionalProperties": false
  }, {
    "title": "One",
    "type": "object",
    "properties": {
      "discriminator": { "enum": [ "one" ], "options": { "hidden": true }}
    },
    "required": [ "discriminator" ]
  }, {
    "title": "Two",
    "type": "object",
    "properties": {
      "discriminator": { "enum": [ "two" ], "options": { "hidden": true }}
    },
    "required": [ "discriminator" ]
  }]
}
```

**Comment by domaindrivendev** [comment]
I had a feeling that might be the answer :). But hey, if it works it works. Thanks so much for your help

**Comment by gfb107** [comment]
Not sure that it is THE answer, but it is AN answer.
