### ISSUE TITLE
Add wysiwyg and markdown formats for `string` editor

### ISSUE THREAD

**Issue by jdorn** [jdorn/json-editor#57]
``` json
{
  "type": "string",
  "format": "html"
}
```

``` json
{
  "type": "string",
  "format": "markdown"
}
```
## WYSIWYG:

Bootstrap:
-  http://mindmup.github.io/bootstrap-wysiwyg/
-  http://jhollingworth.github.io/bootstrap-wysihtml5/
-  http://hackerwins.github.io/summernote/

Non-bootstrap:
-  http://xing.github.io/wysihtml5/
-  http://www.scriptiny.com/2010/02/javascript-wysiwyg-editor/
## Markdown

Bootstrap:
-  http://kevin.oconnor.mp/pagedown-bootstrap/

Non-bootstrap:
-  http://epiceditor.com/

**Comment by aguegu** [comment]
May I ask why you choose SCEeditor? 

Summernote seems to be a much more popular choice.

**Comment by KrishnaPG** [comment]
Is there a way to specify the editor? I would like to use `summernote` instead, due to its support for pasting images. How to do it?
