### ISSUE TITLE
Getting starting value from a JSON file

### ISSUE THREAD

**Issue by xezpeleta** [jdorn/json-editor#582]
Hi!

Is there any easy way to get the starting value (startval) directly from a json file?

I'm using json-editor to edit a JSON file in the server. I already can save the modified JSON using a PHP. Now, I would like to see always the updated file in the editor.

Is that possible?

Thanks in advance!

**Comment by xezpeleta** [comment]
Forget it, I did it using a XmlHttpRequest.

Thanks

**Comment by AnesAb** [comment]
Ive tried it to, with a XmlHttpRequest but it dosent work for me. How did you manage to do it?

**Comment by xezpeleta** [comment]
In the following example you can see that I load a json `events.json` file and I use that as my starting_value

```js

function getJSON(url, callback) {
          var xhr = new XMLHttpRequest();
          xhr.open("get", url, true);
          xhr.responseType = "json";
          xhr.onload = function() {
              var status = xhr.status;
              if (status == 200) {
                  callback(null, xhr.response);
              } else {
                  callback(status);
              }
          };
          xhr.send();
      };

getJSON('events.json', function(err, data){
      if (err != null){
          console.log('Error retrieving JSON file: ' + err);
      } else {
          starting_value = data;
      }
      initJSONEditor();
});
```

**Comment by AnesAb** [comment]
Great thanks alot! My problem was that I didn't initialze the values for the editor. The last line initJSONEditor(); saved me alot of trouble. I just put everything in that function and its working now.
