### ISSUE TITLE
changing schema based on selection/data

### ISSUE THREAD

**Issue by brean** [jdorn/json-editor#619]
Hi,

in my current JSON-Editor Project I have a field labeled "type" that allows the user to select a type. Depending on what he chooses from that it should be possible to enter different things. 
Is it possible to have that in one schema and editor or do I have to create a new editor with a second schema that is based on the selection of the first editor (using editor.on('change'... on the first editor)?

**Comment by codler** [comment]
I wonder also

**Comment by wjy4124** [comment]
I wonder also too..

**Comment by jdorn** [comment]
This is possible with JSON Schema, but it's counter-intuitive.  The trick is to use a combination of `oneOf`, `additionalProperties`, and `enum` with a single value

Here's an example:
```js
{
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      // Hide the 'type' input. Using 'oneOf' will give the user another way to switch between types
      "options": {"hidden": true}
    }
  },
  "oneOf": [
    {
      "title": "Full Name",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": ["fullName"]
        },
        "fullName": {"type": "string"}
      }
    },
    {
      "title": "First and Last Name",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": ["first-last-name"]
        },
        "firstName": {"type": "string"},
        "lastName": {"type": "string"}
      }
    }
  ]
}
```

**Comment by fxi** [comment]
@jdorn using 0.7.28, this example returns the `type` inconsistently. I was expecting the `type` to be returned each time, but it's not the case. [Example with more options.](http://jeremydorn.com/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCokst40ciVYh5AdgOZ7JQUknGvFAALcgBNJMTgnYBXGAF9V+ITADyAMwQBtOuTAAbFiABiC48YAEAOQCGAWzj4H0o+SEPjABWKkFNQI2j5UMPhEJDBklCJ0zIz0ZmwcPHyyCk76INpWxo4uIAC66gJewowS0rLyhEpqufmFLAkMrOxcvI3JCMjoWDjKuIYmZubkhGw2DpySNgAyDtMtfO6Snt5+ATFBIqHG4ZE7scGiTO1tKZ3p+JnZ8Hq5k2wAtMbLYK+cznCl/IJKudqjI5PBFCphs8pmBVudeh00t18B82HCrn1Ul0QD1EohUBhsDiRuAjKY+powGIYjYfkU3B5AT5/NFTvswhECCc9kk8RjEdi7pwsjkkFSYt9fiUyoD4iAQbVwfVIepxYQJjD0Rdrkjicg1Us0VL4XiQFj0rj2v1CUMSRQxn0ALJIQgwWlShkbJnbVk8+AHI5c31xXmXbWYm68IUix4gJwumCSor/EiyqpSUF1BpQ+OuyzWLUIs2RnFQosEwY44rKIAA=&value=N4IgLgngDgpiBcIBmBXANmgcgQwLZwBpl0s85EQBfIA=&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

Thanks :)

**Comment by abop** [comment]
@fxi I dug into the source and found that the problem was cause by the option `keep_onof_values`, of which the default value is true. Set it to false would solve the problem.         
```javascript
JSONEditor.defaults.options.keep_oneof_values = false;
```

@jdorn Maybe it should be added to doc as an FAQ.

**Comment by fxi** [comment]
@abop : Yep, `keep_oneof_values = false ;` solves this problem. [Example.](http://jeremydorn.com/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaZUYAlkgHYDOCoA1jDFAPpkxIBmDAbgIYA2ArjErxWvcjAC++KACcksacUFVw0OPFCRYCEOTDSipAOZ4CxMkNAALIgBMbMUgj0Dxr/MwDyrBAG0NRMB41EAAxPh4eAAIAOS4AWzh8LjsAklJeAAVZeUUhER4xKWyYBSIldRUtCs1g3X0jEwc+ON8QVnCeWISQAF13QjSLEGs7BydpF0k2jq61DVVtOoNjfGJA4LCIyPTut0rg1AxsEzkzCmVaeiZSFnZufnL8sTd/de0QomldSK5SG0iADJcb6zEzJGypMiZYqlR6iGBFOQlXLKGqohaIJYNfBNFrwHxtT66AC0PGBYGJOzgfVMg2UI3sjngzgkU1YRLAoOqGJ0emWJjWQXeHO28TgUzJui58yqvPqK3AASFiCB3ypID2aMQhywOH6ZyGl0YzDYnF4Ajy8JeireiA8YEsJVF3SSKTO0KRsMtBQRIBknpR3KqMtqfOxIFxrSQDpKlLFvX1dIqDLGzImrPcMekHy+nPjQdD8o1mcd0lVee6BcWYeMmp5OuOifMFzoxpupvuFoQTwzr2VIAAskhpDBnYkQODIekeFkA2VvYU/TDAyH0bKsQrI/iQHFhzA490aack1ZbIzxpN8LuR5tOvnV5iaxqplrkOhdScBs2KkbrrczQ8C6sj04hAAAA=&value=N4IgLgngDgpiBcIC2B7ATjAtAOwIZLgBpl0YAxAVwBsqA5fOREAXyAAA&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)  Thanks!
