### ISSUE TITLE
Bug# delete a row of an array and add a row=> this row will be  empty

### ISSUE THREAD

**Issue by kika31** [jdorn/json-editor#623]
Hello,

I have found a bug on array management.
When:
1- I add a row in a array (for example add a "coworker" in examples/recursive.html )
2-delete this row (coworker)
2- add again this row (coworker)
=> the form of the new object coworker is empty.

Please someone have ever seen this bug? Do you have a patch to correct it?

Regards,

**Comment by mmallis87** [comment]
+1.

**Comment by clickfwd** [comment]
I am also seeing this issue.

**Comment by clickfwd** [comment]
I managed to track down the issue to the "add_row_button" click event. Inside this block of code:

```javascript
    this.add_row_button.addEventListener('click',function(e) {
      e.preventDefault();
      e.stopPropagation();
      var i = self.rows.length;
      if(self.row_cache[i]) {
        self.rows[i] = self.row_cache[i];
        self.rows[i].setValue(self.rows[i].getDefault()); //<== PROBLEM
        self.rows[i].container.style.display = '';
        if(self.rows[i].tab) self.rows[i].tab.style.display = '';
        self.rows[i].register();
      }
      else {
        self.addRow();
      }
      self.active_tab = self.rows[i].tab;
      self.refreshTabs();
      self.refreshValue();
      self.onChange(true);
    });
```

If you comment PROBLEM line, then the issue no longer happens because an empty object is not inserted when a new row is added.

**Comment by kika31** [comment]
Thanks for your help
I resolved this problem by initializing each of my array
