### ISSUE TITLE
SCEditor changes no longer reflected in editor.getValue()

### ISSUE THREAD

**Issue by brettz9** [jdorn/json-editor#650]
I'm not sure why but when I updated from 0.7.22 to 0.7.28, SCEditor changes are no longer reflected in `editor.getValue()`. Any idea why?  SCEditor fields do show up, however (set by `JSONEditor.defaults.editors.string.options.wysiwyg = true;` along with `format: html`).

**Comment by brettz9** [comment]
Sorry, I discovered the problem here was actually jQuery.

**Comment by eric-schleicher** [comment]
Always :)
