### ISSUE TITLE
my data seems to be changing on editor load?

### ISSUE THREAD

**Issue by danwf** [jdorn/json-editor#661]
The schema I'm using to initialize the editor is [`examples/meta_schema.json` ](https://github.com/jdorn/json-editor/blob/master/examples/meta_schema.json) (which I plan to modify in the future, but I'm just using the stock json for now), and the data I'm loading in is a JSON schema a user created using this editor+meta_schema. 

It is structured somewhat like this (significant edits made for brevity):

`{
  "type": "object",
  "properties": {
    "dataSource": {
      "type": "object",
      "properties": {
        "userName": {
          "type": "string"
        },
        "queries": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": { (stuff)
            },
            "required": [
              (stuff)
            ]
          },
          "minItems": 1
        }
      }
    }
....`

However, the editor will not include any of the items underneath "queries":

`{
  "type": "object",
  "properties": {
    "dataSource": {
      "type": "object",
      "properties": {
        "userName": {
          "type": "string"
        },
        "queries": {}
    }
....`

Clicking on 'Edit JSON' to view the JSON, or using the getValue() method on the editor will reveal the same change. I have tried using both the startVal parameter when initializing the editor, and I've tried not using startVal and instead using setValue() right afterwards. 

Moreover, once I try pasting the correct JSON into the 'Edit JSON' box and hit 'save', I get the same issue. Sometimes I will see `"queries": {"type":"object"}` or `"queries": {"type":"string"}` (where is it getting string from?!) instead of `"queries": {}`. The only way I have been able to get the data to display properly is by selecting 'Array' on the dropdown in the editor (see pic), and then pasting the correct data back into the 'Edit JSON' box and click save.

![image](https://cloud.githubusercontent.com/assets/18725523/17901172/4a60568c-6930-11e6-90a8-e6501cd0a993.png)

I went through the editor's initialization code in a debugger, and at no point did I see the data change. It seems like this only happens once the editor is actually spit out onto the webpage.

What can I do?

**Comment by oleics** [comment]
@danwf 

> have you seen this issue before when using a meta-schema?

Maybe it was, but right now, it is not an issue for me.

Set the `keep_oneof_values` option to TRUE and try again. And set the schema _and_ the data when creating the editor-instance (`new JSONEditor(el, {schema: schema, startval: data, keep_oneof_values: true})`), this might do the trick. Though, editor.setValue() is also working for me, it's used for Undo/Redo.

**Comment by danwf** [comment]
@oleics Thanks. Unfortunately, no luck.

**Comment by oleics** [comment]
@danwf 
You could create a gist containing the full schema and post the url to it here (https://gist.github.com/) ;-)

**Comment by danwf** [comment]
@oleics https://gist.github.com/danwf/51618e26b1f272bbad28c457bd8121c4

The exact same as `examples/meta_schema.json` except I commented out 'title' from 'defaultProperties'

**Comment by oleics** [comment]
@danwf 
Sorry for not being enough specific, but what I meant was the schema created by the meta-schema. Add all three (meta-schema, created schema and the mentioned data made by the created schema) as .json-files to the gist and I'll have a look at this.

**Comment by danwf** [comment]
@oleics Unfortunately, I'm not able to share the full created schema; the most I can give is the problem area I've posted in the OP. And by "data" I just meant that I was trying to load the created schema into the editor.

**Comment by oleics** [comment]
Yeah, I would like to help you, but for that I really need to reproduce the
problem.

**Comment by danwf** [comment]
@oleics Sorry, was away for a while.

I updated that gist again. To reproduce it, you can: 
- initialize a JSONEditor with 'schema' set to JsonSchemaMetaSchema (from my metaschema.txt) and 'startVal' set to the schema in "createdschema.txt." 
- load it on a page. You should see that what's displayed corresponds not to "createdschema.txt" but to "loadedschema.txt"
- Contrast this with another JSONEditor with 'schema' set to what I have in 'blankSchema.txt'. This behavior doesn't happen.

**Comment by danwf** [comment]
Ok, I think I've fixed it actually. I played around with it on the sample editor and saw that there were some validation errors.

The [first error](http://jeremydorn.com/json-editor/?schema=N4IgJgpgZglgdjALjA9nAziAXKdBjACwgFsBDAQQCdLSBPbURWgBwmxFOrpABoRj4ASUQlMWAIx8kohiAAklaOwDEAekiwEyNOlX4iZXiGSIANmywh9JUiAC+dvnACup07KatZEF8WwBtEBc3EABdRxAfZz8cEGliMUYWCyDXdwcIgCMUFHNSOFlmShRWSmQIRPBoUldED2T2bNyIfPs+TwtQKJjApryC8L5u2XjKjsac/vsIqBRKMjrY8ct0REp4AHMjYaxA9AhzPDq+Qgg8AGtsgA8wjL5V9bgt2KKSiDKYCtkS7QxC4tK5Uq8GYzkQAH0AO4wMCIAj1LwrNabNpxOCgiFEGAbAiLJKIqzIp6oiBXZj5MDgrE4vHGBqWPotAoRSG0dAwVnPfEpRmtO4gWbzUi05aEx5bPivQG0ADylEglGwACYAAxDXwBEB4XJzIxgYVsPj6kTIYiG8AG00QAC0phQeFI7iGZBgTv4aDhRl8mXeRhoT3NIjdIiux2MpMQnBaRitRmclDdkIgEHORlIR1QGDw62YYcywsIsHMRjwJYA1GWS8xmCWUFAoMmS+gCJww3h0Jgja29QArfIbFDbHudyIJ/tGAemcd8DbFFAAN3ofBbcDA5nzlBHLfQ5wObpbV3NuOIbvgMCMfcgF9I89sfD7t/wObDw7QRnMHffMHQNb4pmcd78KQu5FuaZCUOcYAoJCBR8AsU6ZEYxBsgAjm6KCZD2ZzIPOZxGOS+COvh7xuswGzoGh+EEL+IDMLQcJvnwipMc4mRLlYpCfvcDpTkY+BcVY4FMHxlH3Ew/4jug84SsY0IyfOmRPjAuZGFcJ5GLQpDqYMVRQDUpgivSYoohEAhwAAMj4GyeksRnwCIGy+nBZ7ENE2BqrRALvEwcoKsqACspmkFcllPDZ3LsPZECOcx/AuW5WAeVK3myvKvpYAAzCqETkogIiUAUtkEg8KJ8IKCzsIojk3JKXllKlfmZYF7T0l0Gq7MZxI6TsoCjAiKQlcSDhwRAYAwLYRUpBhWFHGmYBjb8joAAp1UC2B6aY+y1W8HxfJN/XsINWz8iIxDMFOIgHUi4rTBE3rpaAyW7ZUPyZpUT1rbEIJglCMLhXSxVEsdUjoj91K4ldnXA5EZIUlSEDYhD+0MpMTK3S1iJtQlgT3Yq3Xtb1p1jEZuPTEa1S1JDpOmfFMQRZYpPbdKvnpUqzVAVcMCuXTAMpIznk7T5aWKpl2VwbUynmDKUBU9EPqxR9DXpRlgXDWiDkPQLgKfC9uZvf8gs6yMoMQtCsLwsjUOot9mIIzSkNHSSsOrvDiOGQSvLMmrGj6e7KRRTFqJmVzCX06kxDy/hq1KyLbNBZz3OyxHTlaylLMi1lpkS+dEDS0nkdM2nwvYCrETLFjPTq9Fvr46HcRE5DAe+hkETWGQABCnGdLz7DTdhc0LZmy2rUbWAbVtum+ytht7YEJjFhjbChHwr06JDfezSvetr7Eu4QMw4JoBAdbgre/57ePEARD7lM4DlI97RX4Lz4/PeWJwNDsc4CAoc4EDCDILAaw/5lTmBVSwkZMgL3roAsOjt2hIGLBAxBbA1azhhOCbU/5iB/Etk3WKwdE4SDgsFEOMRxBKgiAQGEkBCph09qiPeB8j4nzPn/YmHtUZ8jVh9Ue9NHrR3TtgSQb8rZb1+JUah80fDYGAVfCIMIHZAyMOVYU7B4zngiHINuE04HKNAUKRYIANGohfkom6hd6pCKwJQ8mSlt50NEfA1OVji5YAACzXwpgZA2zM3HiDFpEAmoiP7cGcnAABCRhF8G/jAX+/8G5AMoCAlxQtGr+UCd0AAyigeMeBu5HzzrsRgKD2BZK5jnAABDkvJgYjKO0cCUswKQADCKAzrmCuNU3JlB8kxiMqE9iqijGQJHGZSJYgRF9ViIUmWxTjClMsG0jAkY4CIEqQANUdOw/pBJBkqLAWoiBpAoHmlifEiZsjkkQCkIkvRN1hpNKQSAGpvS6kEg3mGUg80kBD1MNPbWF9HQT0UL/GAigwCanQD0vpy9J61ABd5UeewYVL0sZ9XAqLvhwFznM/wTyUgAHUCxEDAJUgAYp8UwkLF6HWUY0hZzT2DLNWPkdZWzz4jlFPsgx4DjAnOgeMxJUy7mMueWw95U1ML9z4N8weaBh4zzEJfdFfCQASvMSZBBTLLYNIyDpdApgYB9MtjygUhyRkCrAkIRJSoSFXEuTY25sDRH4LJgKV0+VNVDW1Ug+5Wr1XbO7qKPVdhwhhq0YoOZ/qfUgFmbIBQShLBqA0GeCRehThkCoJ/VE+RZTRvkFGlQ6hoBprehmgwFAuD0AiI6UwRTQCJrmSAFNpatDlp0dm7gd0UC0ibcW1N7adAVpsKiRW1iw78xvj4iQKo50RCNXAc4HCUhmumWHT5MZFkgEXamWVPzFr/Ifsq4FNzUlqsUO4XV9LlxFuvRY81hj1EJlRHgKcn570BqgjBO03zsW4oCPQrhzIeAxuOjpM0Y1SAABVWpOPpfySEJL17Ss3rRYU+U4CIuerIAAdAAKm9cdNWRBvnvGgyQc6BoiPozjah2k07EDYc+oEXhXw4Vsd1hI3xSLX5YKnMwfYkLLYMOvt+K1mDcgCf2JDUTRpxOnPBKNJA4JXyONFHJ8ACnzDgk47J4DqJFDEAXBAJTZ0mC6ePfp5ofI/x0FyX7OlD6diBHQZC8NZc4MubozNOoOlGMod82OqzltN2Sgw+8LDIXQAEYTXeltJbNC/OHTo2juVMPMbVaKML6G8qRcy6/WLsR+3JsS2WlLmbbD8jlcluAirAUromDZkDIBQXOHBaNSGZrzl/0dXI3lRz+WnKMOu+DD6zGWEVu64ZNH1TYxAG524at9mxEYwVsQgQ+ocei3Ghx70dv8dIIJzrImDNifQBJwZ4I5XWamOdy71bwSQHMJdU7zXURjQu4pq7z2IAiGu24cExRISNZRu9+733Hu/f+++iEwPbtowhzpq7ig5iNSA+D+TX2dOHeOwj7hnnMZBPm/s/z3jHPv2rdbUVJWEuDtq7oVLEQesJJdRps74THVhzdeEsh7l45c9dWs6uBDab8/3fKurphBe09bUl9NTOBsU7EcTyuZrIHQNGSWIgFxrh8QOP3Dz3FK1xaTXTttDOR0dy7kYVeuDQBMMPji1hQaT2bSvuTPSt8N30dRPG+ZE2Xn6MLWbuX5WMB6BvQS9gAA5OWKdZdlaHRH6moGxUpEEMLwOfBE/0/TW6hlgf24GZz/FsPyfdByej5YGUvvS+h6T5bzdhft1dvYrni36b9kt51SAOPIR6/NvL5b4I6Q0+B5jygSpsGvCD4HZ3jtlXO4yYjWXbdAApLJMoY/VMq0YDv8vF8m9Va/PP+tQt19yxlnbRXG1l8bwrvfLc7BAAAA==&value=N4IgLglmA2CmIC4QgDTgJ4Ad5IPYCMArWAYzFREwCddsrJYBnRYAX1aA&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&show_errors=interaction) was related to 'additionalProperties', so I set that to 'true' in 'schemaBase'. Then, I got some [additional errors](http://jeremydorn.com/json-editor/?schema=N4IgJgpgZglgdjALjA9nAziAXKdBjACwgFsBDAQQCdLSBPbURWgBwmxFOrpABoRj4ASUQlMWAIx8kohiAAklaOwDEAekiwEyNOlX4iZXiGSIANmywh9JUiAC+dvnACup07KatZEF8WwBtEBc3EABdRxAfZz8cEGliMUYWCyDXdwcIgCMUFHNSOFlmShRWSmQIRPBoUldED2T2bNyIfPs+TwtQKJjApryC8L5u2XjKjsac/vsIqBRKMjrY8ct0REp4AHMjYaxA9AhzPDq+Qgg8AGtsgA8wjL5V9bgt2KKSiDKYCtkS7QxC4tK5Uq8GYzkQAH0AO4wMCIAj1LwrNabNpxOCgiFEGAbAiLJKIqzIp6oiBXZj5MDgrE4vHGBqWPotAoRSG0dAwVnPfEpRmtO4gWbzUi05aEx5bPivQG0ADylEglGwACYAAxDXwBEB4XJzIxgYVsPj6kTIYiG8AG00QAC0phQeFI7iGZBgTv4aDhRl8mXeRhoT3NIjdIiux2MpMQnBaRitRmclDdkIgEHORlIR1QGDw62YYcywsIsHMRjwJYA1GWS8xmCWUFAoMmS+gCJww3h0Jgja29QArfIbFDbHudyIJ/tGAemcd8DbFFAAN3ofBbcDA5nzlBHLfQ5wObpbV3NuOIbvgMCMfcgF9I89sfD7t/wObDw7QRnMHffMHQNb4pmcd78KQu5FuaZCUOcYAoJCBR8AsU6ZEYxBsgAjm6KCZD2ZzIPOZxGOS+COvh7xuswGzoGh+EEL+IDMLQcJvnwipMc4mRLlYpCfvcDpTkY+BcVY4FMHxlH3Ew/4jug84SsY0IyfOmRPjAuZGFcJ5GLQpDqYMVRQDUpgivSYoohEAhwAAMj4GyeksRnwCIGy+nBZ7ENE2BqrRALvEwcoKsqACspmkFcllPDZ3LsPZECOcx/AuW5WAeVK3myvKvpYAAzCqETkogIiUAUtkEg8KJ8IKCzsIojk3JKXllKlfmZYF7T0l0Gq7MZxI6TsoCjAiKQlcSDhwRAYAwLYRUpBhWFHGmYBjb8joAAp1UC2B6aY+y1W8HxfJN/XsINWz8iIxDMFOIgHUi4rTBE3rpaAyW7ZUPyZpUT1rbEIJglCMLhXSxVEsdUjoj91K4ldnXA5EZIUlSEDYhD+0MpMTK3S1iJtQlgT3Yq3Xtb1p1jEZuPTEa1S1JDpOmfFMQRZYpPbdKvnpUqzVAVcMCuXTAMpIznk7T5aWKpl2VwbUynmDKUBU9EPqxR9DXpRlgXDWiDkPQLgKfC9uZvf8gs6yMoMQtCsLwsjUOot9mIIzSkNHSSsOrvDiOGQSvLMmrGj6e7KRRTFqJmVzCX06kxDy/hq1KyLbNBZz3OyxHTlaylLMi1lpkS+dEDS0nkdM2nwvYCrETLFjPTq9Fvr46HcRE5DAe+hkETWGQABCnGdLz7DTdhc0LZmy2rUbWBrM4EDk3ptQrYbe2BCYxYY2woR8K9OiQ33s1r3rG+xLuEDMOCaAQHW4K3v+e0bfsEQ+5TOA5SPe0V+Ci/Pz3licDQ7HOAgKET8IGQY9KATzKnMCqlhIyZCXvXIBYdHbtCQMWSBSC2Bq1nDCcE2p/zED+JbJusVg6JwkHBYKIcYjiCVBEAgMJICFTDp7VEB8j4nzPhfCexMPaoz5GrD6o96aPWjunbAkgP5Wx3r8SoND5o+GwOPCAasYQOyBkYcqwp2DxnPBEOQbcJrwJUWAoUiwQCaNRG/ZRN1C71WEVgKh5MlK73oWIhBqdrHFywAAFlvhTAyBtmbuPEGLSIBMxFf24M5OAgCEgiL4L/GA/8IBRLEPIqxQtGr+SCd0AAyigeMeBu4nzzrsRgqD2BZK5jnAABDkvJgYjKO0cCUswKQADCKAzrmCuNU3JlB8kxiMmE9iajjFQJHGZJJMTYHRNiIUmWxTjClMsG0jAkY4CIEqQANUdBw/pBJBmqPAeoyBpBoHmjiQkiZwDQFTM4QNFRw0mnIJADU3pdSCRbzDKQeaSAh6mFntrK+jotogEUP/GAigwCanQD0vpq9dK+3+d5UeewYUr1SfwqwqLvhwFznM/wjyUgAHUCxEDAJUgAYp8UwkLl6HXuTwAl7BlmrHyOsrZl8Ryin2YYiBxgTkwPGQ3EhNyPCLJAOwt5U1ML9z4F8weaBh5zzENfSerjPqgAlRYkyiDmlaqGhkHS6BTAwD6ZbblApDkjP5WBIQQqlSkKuJc+1Ir8FrOroqNWRZ8p6uhuYy2DS+Cav9fchw4Q7A6QUEoYNN0IizNkJGuZIA1AaDPJIvQpwyBUG/qifIso5mgATSodQ0BU1vXTQYCgXB6AREdKYIpBbFCJuTSWrQZbdFZu4HdFAtJC2WGbZoH5Ohy02FRIrGxYd+Z318RIFUs6IjGrgOcW57BzV9Uth8mMYqF2plld8xafyn7KqBaqvh79FDuGjdqkABBG0+oOUYjRCZUR4CnJ+S9Q0jTQTgHaL52LcUBAYdw5kDLnH3J0maMapAAAqrVQMxv5JCElm9pXb1osKfKcBEXPVkAAOgAFR3v5EQL57woMkHOgaQjasN2xCnYgLDn1AinswHC5j3xHHvUPbIbBU5mD7EhZbRht9vzWqwbkXj+xIZCaNCJ054JRpIHBK+JxoppPgFk+YcEbHBNAdRIoYgC4IDybOkwLTXGdPND5H+OguS/Z0sscE7GIAMGQrDWXWDOxAgbp0nR5DM06iPyVX5mVaG8rvEw+Z0A+H423r7cWgdabdHo1CxhhjGLRQbslOh8LaX37RdiL2pN8XS1DqS/yOVg64CKoBculGlngMgogGCiFkNzXnIAUKlJFqH3HNOUYNd+iHN+rVdWmYlq73qicy524at9m0Z8fR8zgQ+qsciyAdeeDBFBdiDx0gfHRpSd08J9AonBngjlYd+rqIxonbk2dyA5hLoWamMd07VbwQPYgCIc7bhwTFEhLVkAambtve/h9g4X2jOvohP9y7L2ZO3c02dxQcxGqAau69uTu39tw7RidDz7VAj7J8wt1rVbrZCobVGorKbW2lYzbYCI7XEmU7EWpwVcCxEEKQrTdy8dLlh25xE8hfPd3yqq6YAX8hYs05bZV3QZWeVHMG6VRzldzVQJgaMksRALjXD4hD2abnuIVpi9T/tJWMDDo7l3IwG3KjMOPjith2zAWbQUVPX2wXZqxpxUU/FCzdWWCyQY6X5vit06twGxllgABycsU6FYt5H3Q1MQPDcEG6wOfAk8R/l6obnjTA9PPbrpnPMvk/5+kzHkAMoUNhlz7T/PG6i/DY7exRvcu037Nb2K+PIRy/h6b2m4I6R0995QJUmDXhB9Nrz4lhnndJPhrVsNgAUlkmUsfqkM6MJ3hLbbd/ovfsP/W676/4WywVXLlR8tU7n6f+npuW52CAAAA&value=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCoKANgIYAWt40cijhhjEeIcmBgBbGvFCRYCZOiw58REjDKVxwAL5atQAA=&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&show_errors=interaction) saying that it validated against 2 schemas when it expects exactly one. I took out 'No Type' from the 'oneOf' element and it finally validated. [Working](http://jeremydorn.com/json-editor/?schema=N4IgJgpgZglgdjALjA9nAziAXKdBjACwgFsBDAQQCdLSBPbURWgBwmxFOrpABoRj4ASUQlMWAIx8kohiAAklaOwDEAekiwEyNOlX4iZXiGSIANmywh9JUiAC+dvnACup07KatZEF8WwBtEBc3EABdRxAfZz8cEGliMUYWCyDXdwcIgCMUFHNSOFlmShRWSmQIRPBoUldED2T2bNyIfPs+TwtQKJjApryC8L5u2XjKjsac/vsIqBRKMjrY8ct0REp4AHMjYaxA9AhzPDq+Qgg8AGtsgA8wjL5V9bgt2KKSiDKYCtkS7QxC4tK5Uq8GYzkQAH0AO4wMCIAj1LwrNabNpxOCgiFEGAbAiLJKIqzIp6oiBXZj5MDgrE4vHGBqWPotAoRSG0dAwVnPfEpRmtO4gWbzUi05aEx5bPivQG0ADylEglGwACYAAxDXwBEB4XJzIxgYVsPj6kTIYiG8AG00QAC0phQeFI7iGZBgTv4aDhRl8mXeRhoT3NIjdIiux2MpMQnBaRitRmclDdkIgEHORlIR1QGDw62YYcywsIsHMRjwJYA1GWS8xmCWUFAoMmS+gCJww3h0Jgja29QArfIbFDbHudyIJ/tGAemcd8DbFFAAN3ofBbcDA5nzlBHLfQ5wObpbV3NuOIbvgMCMfcgF9I89sfD7t/wObDw7QRnMHffMHQNb4pmcd78KQu5FuaZCUOcYAoJCBR8AsU6ZEYxBsgAjm6KCZD2ZzIPOZxGOS+COvh7xuswGzoGh+EEL+IDMLQcJvnwipMc4mRLlYpCfvcDpTkY+BcVY4FMHxlH3Ew/4jug84SsY0IyfOmRPjAuZGFcJ5GLQpDqYMVRQDUpgivSYoohEAhwAAMj4GyeksRnwCIGy+nBZ7ENE2BqrRALvEwcoKsqACspmkFcllPDZ3LsPZECOcx/AuW5WAeVK3myvKvpYAAzCqETkogIiUAUtkEg8KJ8IKCzsIojk3JKXllKlfmZYF7T0l0Gq7MZxI6TsoCjAiKQlcSDhwRAYAwLYRUpBhWFHGmYBjb8joAAp1UC2B6aY+y1W8HxfJN/XsINWz8iIxDMFOIgHUi4rTBE3rpaAyW7ZUPyZpUT1rbEIJglCMLhXSxVEsdUjoj91K4ldnXA5EZIUlSEDYhD+0MpMTK3S1iJtQlgT3Yq3Xtb1p1jEZuPTEa1S1JDpOmfFMQRZYpPbdKvnpUqzVAVcMCuXTAMpIznk7T5aWKpl2VwbUynmDKUBU9EPqxR9DXpRlgXDWiDkPQLgKfC9uZvf8gs6yMoMQtCsLwsjUOot9mIIzSkNHSSsOrvDiOGQSvLMmrGj6e7KRRTFqJmVzCX06kxDy/hq1KyLbNBZz3OyxHTlaylLMi1lpkS+dEDS0nkdM2nwvYCrETLFjPTq9Fvr46HcRE5DAe+hkETWGQABCnGdLz7DTdhc0LZmy2rUbWBrM4EDk3ptQrYbe2BOMoR8K9OiQ33s3L3rq+xLuEDMOCaAQHW4K3v+e0bfsEQ+5TOA5SPe0V+CJgfpDnA0OxzgIChE/CDIY+UBPMqcwKqWEjJkYsUgG6W0du0JAxZQFwLYGrWcMJwTan/MQP4lsm6xWDonCQcFgohxiOIJUEQCAwkgIVMOntUS733ofY+p8J7Ew9qjPkasPqj3po9aO6dsCSB7tdUqIAV5YNABQ+aPhsDjwgGrGEDsgZGHKsKdg8ZzwRDkG3CaYcYECmAaoyw6jUTP27qKPRit+FYDIeTJSW9qFCKtoXeqViAAsV8KYGQNszYuEgxaRAJo4t+3BnJwF/gkARfBP4wG/hAcJYhZHOKFo1fy/jugAGUUDxjwN3Q+eddiMEQewdJXMc4AAJMnZMDEZR2jhClmBSAAYRQGdcwVwKlZMoDkmMRlgnsRUYsYwpBFJISEFAwRfVYh5JlgU4wRTLDNIwJGOAiAykADVHQsJ6QSPpyiDGDLARAkA0TYnxJkQAye9c/66KUcNep8CQCVK6dUgk68wykHmkgIephZ7a3Po6LaIBFDfxgIoMAmp0CdO6UvXSvtfneVHnsKFbAYVcIflYZF3w4C5xmf4e5KQADqBYiBgDKQAMU+KYcFGMBq3J4Pi9gizVj5FWRss+I5RS7KAUKA5wyjlmTOQQq5ESljzJAMwl5U1ML9z4B8weaBh5zzEBfS5aLKgSsUTdMu8yblaoyDpdApgYDdMtly/RPL2CHLAmMv+SpCFXEFXa4VrD/YrOroqNWRZ8qapMrAhpPqhp8A1dA25Dhwh2B0goJQIatXL2xfk0AUaZkgDUBoM8vxdDaKoO/VE+RZQzMTYoZNqboDprenoU4ZBs3cAiI6UwCb5BFpUOoUtWhy1Zq4PQO6KBaRJubWmttOgK0GFsHfQWMd84p2vl4vxKp/FGrgOcF17AzWTLDm8mMYqF2pllZ8xaPz77KoBaqw9shFDuBjb6kABAm2XuJNykBxyEyojwFOT8d7oZQRgnaD5WKcUBBoew5k9LHG1J0maMapAAAqrVQOhrVpCYla9pUb1osKfKcB4XPVkAAOgAFQBuOmrIgHz3hQZIOdA0hH0aiJQ7SadiAsOfUCGqsISTuGiPse9U9sR0FTmYPscFltaFX2/HyiAaDcj8f2JDETRoxPgIk6NJA4JXwONFHJ8ACnzDglY8JoDqJFDEAXEps6TBdM8cA80Pkf46BZL9odJR6psYgBQeC8NHjp4zvXXRkxsGdiBA3TpPTPmZphlyhhpjHH8OyD7ZYEtmgvlDu0TRiL7xMOWccRuyU6H0tRfRTF2IcWU0tsSxm4dNgaNyqS3ARVfzl0o2s8BoFEAQVgtfp2uMX8f5QMSeax9VqjBrrgzdP1DzFZk364Y3VIiAuufWO5/kuzYgMfy2IQIfVUWZbEdxpVsg+OkAE6NWTBnRPoHE+CPpl35onaa6iMa53FOXc7eCSA5hLr6bu2di7V23sQBEJdtw4JiiQgayATTD2fsvb+wDt9EIQe3amN9p7V3FBzEalZpH8nHs6YO0dxHaN+QMY6zmsu/n2qBF2TpYbxWEtluS5W0dUTutxKgZjwnoTBVhxwaMhA+D/FkAdWzxxPPQnEPcrWvd3yueNujSVgdNXM2M9RAM6jznK5msG+0YZI5TgXGuHxA4/cPPcRHbF298vW2K4qx3LuRgduyHoQfbFTDNn/M2nIqevtkNhdRNMgDcz/WWHSU52XxbSv04wHoOlDLLAADk5Yp1pxHwdUfqYgdMewQQbrA58GTwr8rPO6mB4ee3AzeeLd09T7oOTseQAyl8xXuXVfrcbuL5nyw1b2L56t+V3Z7exUJ5CE38PBfy3BHSOGsbKQABS6SZRx4qcrkf/be/tuX6nbDK21/b1CzKtDeU8uZcK4W5vKfrcpZbnYIAAAA==&value=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCwAvnUAAA=&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&show_errors=interaction)

This is sufficient for me because my users don't need 'No Type' as an option. If that seems like it's a common thing, maybe we should update the meta-schema that's in this repo? I have posted my working meta-schema [in that same gist](https://gist.github.com/danwf/51618e26b1f272bbad28c457bd8121c4#file-working_metaschema-txt).

**Comment by jinwyp** [comment]
@danwf  thanks your work. 

I have a problem with your working demo.  when select different type, "string", "integer" or other types.  Sometime the "type" property didn't output in the right JSON Output box. 

Sometime output like this below 

```
{
  "type": "object",
  "properties": {
    "aaa": {
      "properties": {}
    }
  }
}
```

It should be 

```
{
  "type": "object",
  "properties": {
    "aaa": {
      "type": "integer",
      "properties": {}
    }
  }
}
```

**Comment by marctc** [comment]
@jinwyp same here. Maybe it will be better open a new issue addressing that.
