### ISSUE TITLE
How to update editor with dynamically filled in data?

### ISSUE THREAD

**Issue by szhangpitt** [jdorn/json-editor#663]
I set up the JSON editor as documented. In my workflow there is some jQuery click handler on the text input element with some script dynamically populating text in. But when I call `editor.getValue()` later, the returned data does not have the updated value. 

``` js
$('#json-editor input').on('click', function (e) {
  $(e.target).val('abc');
});

//.. later
var data = editor.getValue();
// data is not updated
```

Any idea what is missing? Thanks.

**Comment by danwf** [comment]
You might have to manually call `editor.setValue()`, give that a shot

**Comment by kirkins** [comment]
Did anyone get the setValue function working? I'm trying to load json dynamically into the editor.

    editor.setValue(validJson)
