### ISSUE TITLE
Is it possible to hide some parent title ?

### ISSUE THREAD

**Issue by andyforever** [jdorn/json-editor#669]
For example, I have this json schema,
```javascript
{
  "type":"object"
  "title": "Parent Title"
  "properties": {
    "child1": {
      "type":"string"
      "title": "Child1 Title"
    },
    "child2": {
      "type":"string"
      "title": "Child2 Title"
    }
  }
}
```
When create the form, is it possible not display the "Parent Title"?
Because I have a complex json schema and the form editor was nested.

**Comment by schooley** [comment]
I assume you don't want to remove the parent title from the schema because you want it there unless the children have a title?
You can use a template engine (like EJS) to handle this sort of behavior.
`headerTemplate: "<%= self.child1 && self.child1.title ? '' : title %>`

**Comment by andyforever** [comment]
Thanks.I extend a boolean property named "hideTitle" in the schema .And I modified the source code to support this.
