### ISSUE TITLE
Update Schema default values later using an actual valid JSON (with different values)

### ISSUE THREAD

**Issue by sandakith** [jdorn/json-editor#681]
I am new to this project and I tried to see if my requirement can be done using json-editor. Basically what I am thinking of is to initially load a schema with default values in the json-editor and later point to a actual valid JSON (with different values) and update the UI displayed values - with a refresh. I hoped this would be one of the main requirements, however I am having trouble to find related information. 

Any comments or pointers would help. Look forward to hearing from you all.

**Comment by TrevorPage** [comment]
Just use `setValue()`.

**Comment by sandakith** [comment]
Thank You!
