### ISSUE TITLE
Similar array behavior for objects

### ISSUE THREAD

**Issue by Rictus** [jdorn/json-editor#687]
Hi.
I understand that having this as schema :  
```json
{
  "properties": {
    "users": {
      "type": "array",
      "format": "table",
      "items": {
        "type": "string"
      }
    }
  }
}
```
will generate controls for each items in the array. But that's for arrays. 
I need the same behavior for objects where instead of iterating through index, it should iterate through keys. (And give the ability to add/remove and change the key).
My data :
```
users: {  
    "12548":{...},
    "39541":{...},
    ...
        }
```

I've searched in issues, I've read the documentation but I think that's not yet possible.
Can you help me ?

**Comment by step307** [comment]
Using patternProperties instead of properties you can define unlimited number of numeric properties with similar schema.

**Comment by Rictus** [comment]
Thank you, that's exactly what I was looking for.

**Comment by yingliangzhang** [comment]
@step307  @Rictus  Could you give me an example of how to use `patternProperties` in this case? I can't find any. Thank you!

**Comment by Rictus** [comment]
Following my previous example : 

``` json
{
  "properties": {
    "users": {
      "type": "array",
      "format": "table",
      "items": {
        "type": "string"
      }
    }
  }
}
```
If in my json data, users are classified with their ID as a key in a object : 
``` json
users: {  
    "12548":{...},
    "39541":{...},
    ...
        }
```

json-editor can generates controls for each id with a given regex : 
``` json
{
  "properties": {
    "users": {
      "type": "array",
      "format": "table",
      "patternProperties":{
            ".*": {
              "$ref": "./schema/user_definition.json"
            }
        }
    }
  }
}
```

**Comment by step307** [comment]
read more: https://spacetelescope.github.io/understanding-json-schema/reference/regular_expressions.html

**Comment by yingliangzhang** [comment]
@step307 @Rictus Thank you very much!!
