### ISSUE TITLE
Is there a way to reset/reload/replace an editor's schema?

### ISSUE THREAD

**Issue by yingliangzhang** [jdorn/json-editor#717]
Hi,

I have an editor that loads the schema from a `json` file, like below:

```
let editor = new JSONEditor(document.getElementById('questionaires'), {
      schema
});
```

The schema file `questions.json`
```
{
  "title": "Questionaires",
  "type": "object",
  "properties": {
    "q_1": {
      "type": "string",
      "title": "Question 1",
      "description": "This is question one",
      "propertyOrder": 1,
      "format": "input"
     }
  }
}
```

Is there a way that can replace the editor's schema after the initialization? For example, I later created a new object:

```
let anwsers = {
       title: "Anwsers",
       type: "object",
       properties: {
            "a_1": { 
                "type": "string",
                "title": "Anwser 1",
                "description": "This is anwser one",
                "propertyOrder": 1,
                "format": "input"
            }
       }
};
```

How could I replace the existing editor's schema with this new object? I tried to do `editor.schema = anwsers` but no luck. I also tries just to replace just the `properties` object, for example `editor.schema.properties = someNewProperties`, doesn't work.

Thanks!!

**Comment by yingliangzhang** [comment]
OK, I get it working by `destroy` the editor first and re-initialize it. Like below:

```
editor.destroy();
editor = new JSONEditor(document.getElementById('questionaires'), {
     schema: anwsers
});
```

This process seems quick enough that the user won't notice the HTML is removed from the DOM first.

But I'm not sure if this is the correct way to achieve this.

**Comment by lbischof** [comment]
See here: https://rawgit.com/jdorn/json-editor/master/examples/advanced.html (Restore to Default)
```
editor.setValue(starting_value);
```
You could also use the ajax features that are shown in the advanced example
