### ISSUE TITLE
Is there reactJS version?

### ISSUE THREAD

**Issue by liubin1777** [jdorn/json-editor#746]
Can you write a reusable reactJS component version?

**Comment by coltonTB** [comment]
See https://github.com/mozilla-services/react-jsonschema-form

**Comment by dapicester** [comment]
Hi, I have been able to wrap this into a React component using [refs](https://reactjs.org/docs/refs-and-the-dom.html). What I have done works but required some extra work using component state and lifecycle methods to ensure that everything is properly rendered.

If anybody is interested I may be able to patch up a gist to share.

**Comment by tkuben** [comment]
@dapicester can you post a patch here please.

**Comment by loganvolkers** [comment]
Unlikely this project will be ported to React. See the mozilla form for an alternative:  https://github.com/mozilla-services/react-jsonschema-form

@dapicester feel free to provide a react wrapper as a gist or separate project

**Comment by dapicester** [comment]
For me, the main issue with the mozilla alternative is that it wraps a everything in a form. In my use case I just needed to render part of my form with a JSON editor, that's why I decided to wrap this library.
