### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by donnyv** [jdorn/json-editor#800]
I noticed there hasn't been a commit in over a year.

**Comment by blalan** [comment]
Also interested in using this in a project. 300+ PR open!?! Some of them would be really great to have in master for my project. Would it be best to fork this and add the PRs in that I would use giving credit? Seems like the community is interested in keeping this updated...

**Comment by schmunk42** [comment]
We cherry picked several PRs on a fork: https://github.com/dmstr-forks/jdorn-json-editor/tree/develop

Feedback welcome. 

@jdorn Please let us know, if you want a PR for those combined changes.

**Comment by geertvanbommel** [comment]
@schmunk42 Did you remove the inline styles as in PR #346 ?

**Comment by schmunk42** [comment]
@kanabanarama can you shed some light on @geertvanbommel 's question?

**Comment by ncelerier** [comment]
Hello, 

I'm interested by this feature implemented in this change request: https://github.com/jdorn/json-editor/pull/647. Could you implement it in your fork ? 

Also there a no way to create issues in your fork project, I think it might be nice if you could enable it rather than being force to come here and ask for PR :-)

**Comment by loganvolkers** [comment]
There seems to be a good community using this project, it seems very popular.

Here's my proposal:
 - Everyone agree to make https://github.com/json-editor/json-editor the new primary fork
 - Release a new version on NPM (Using semver plz)
 - Submit an application to the JsFoundation: https://js.foundation/
 - Write a blog article about the above
 - Comment on individual issues and PRs and request people move their issues to the new repo
 - Talk to @jdorn if he ever returns from the dead

Potential list of future owners:
 - @schmunk42 
 - @Kanabanarama

**Comment by xvaara** [comment]
I invited @loganvolkers @schmunk42 and @Kanabanarama to the json-editor org as owners. Accept if you like. I don't have that much time to put in to maintaining it, put pull requests are welcomed.

**Comment by gradinkov** [comment]
Has the submission been rejected? Or it wasn't submitted at all?

**Comment by schmunk42** [comment]
There's a "stable" version available on master at https://github.com/json-editor/json-editor

But we're unable to release under the proper org at the moment, see https://github.com/json-editor/json-editor/issues/5#issuecomment-371251860

**Comment by gradinkov** [comment]
I meant the js.foundation submission :)

**Comment by schmunk42** [comment]
Project lives now here: https://github.com/json-editor/json-editor

**Comment by santurak1** [comment]
- [ ] Santuraki foundation founder Ai https://github.com/user-attachments/assets/4ebb6a98-2d14-4b94-b406-5b899f84e51b
