### ISSUE TITLE
Array's enum's empty default breaks if deleting an array element

### ISSUE THREAD

**Issue by gradinkov** [jdorn/json-editor#813]
If an array's enum's default is { }, and you delete any array element, you're unable to select the enum anymore.

**Comment by schmunk42** [comment]
This repo is no longer maintained (see also https://github.com/jdorn/json-editor/issues/800)

Development is continued at https://github.com/json-editor/json-editor

For details please visit https://github.com/json-editor/json-editor/issues/5
