### ISSUE TITLE
Custom validations working but select is not showing errors in DOM.

### ISSUE THREAD

**Issue by aseem2625** [jdorn/json-editor#819]
**Property is defined as:**

```
    "location": {
      "type": "string",
      "title": "Location",
      "enum": [
        null,
          "city1",
          "city2",
          "city3",
      ],
      "options": {
        "enum_titles": [
          "--Select--",
          "city1",
          "city2",
          "city3",
        ]
      }
    }


```

**Custom validation added using:**

```
JSONEditor.defaults.custom_validators.push(function(schema, value, path) {
var errors = [];
if(some_condition) {
    errors.push({
        path: path,
        property: 'format',
        message: 'Some custom message on select'
    });
}

return errors
});

```

On `var errors = editor.validate();`, `errors` correctly contains the error as per the custom validation above, however, just for the **Select** element, `has-error` class and `<p class="help-block errormsg">` are missing from DOM. For custom validators on other `type=string` fields, everything working fine.

Is there any way to implement this?

**Comment by schmunk42** [comment]
### Deprecation notice

This repo is no longer maintained (see also https://github.com/jdorn/json-editor/issues/800)

Development is continued at https://github.com/json-editor/json-editor

For details please visit https://github.com/json-editor/json-editor/issues/5

**Comment by aseem2625** [comment]
Raised here..  https://github.com/json-editor/json-editor/issues/123

Thanks
