### ISSUE TITLE
using enum's as foreign keys

### ISSUE THREAD

**Issue by snowch** [jdorn/json-editor#82]
I have a relatively flat json structure that reflects a few database tables, with foreign keys represented as enum watch fields.

When a user uses the editor to add a row to an object that has enumSource field that points to another object's field, the row's enum field is pre-populated with the first item in the array of the pointed to object..

Is there some way that I can set the enumSource ids to be empty rather than them defaulting to the first item in the pointed to array so that the user has less chance of making an error by leaving the preset value as the choosen item?

**Comment by briandastous** [comment]
It seems like that schema (using {{item.id}} as suggested) now produces this error in the demo in Chrome:
`Uncaught TypeError: template.match is not a function`

**Comment by aiht** [comment]
If anybody else is having the same problem, I found that a way to fix the `template.match is not a function` error above is to change the section

    "enumSource": [
      ["none"],
      {
        "source": "o",
        "value": "{{item}}"
      }
    ]

to

    "enumSource": [
      "none",
      {
        "source": "o",
        "value": "{{item}}"
      }
    ]

where the `"none" ` has been changed from a nested array to a plain string.
