### ISSUE TITLE
how to add or modify description on json schema

### ISSUE THREAD

**Issue by jackson19921109** [jdorn/json-editor#829]
if i want to add or modify description on json schema , and i don't want to change it on the json schema string , I just want to do it on the html form page, is there any api to do this ?

**Comment by john-nance** [comment]
Just set the title property to the value you want to see in the form

    "propertyName": {
                    type: "string",
                    title: "Friendly name"
    }

**Comment by Houfeng** [comment]
Try using sditor : [https://github.com/Houfeng/sditor](https://github.com/Houfeng/sditor)

**Comment by pmk65** [comment]
> 
> 
> if i want to add or modify description on json schema , and i don't want to change it on the json schema string , I just want to do it on the html form page, is there any api to do this ?

@jackson19921109 Dunno if it works with this version of the library, but it works using the updated version available at: https://github.com/json-editor/json-editor

Example of changing label and description at runtime: https://is.gd/ktVrQQ
(Label and description of 1st element is changed after form is ready.)
