### ISSUE TITLE
readonly is not documented

### ISSUE THREAD

**Issue by vassbence** [jdorn/json-editor#836]
You can make properties read-only by using the "readonly: true" option. Actually it's not even used under options, you can use it like this:

    some_prop: {
      type: 'boolean',
      readonly: true
    }

This could be documented IMHO, it was useful for us.

**Comment by pmk65** [comment]
This repo is no longer maintained (see also #800)

Development is continued at https://github.com/json-editor/json-editor

For details please visit [json-editor/json-editor#5](https://github.com/json-editor/json-editor/issues/5)
