### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by afterclassroom** [jdorn/json-editor#88]
Hi ,
- How to create scheme that contains file upload input?
- Is there any way that we could implement additional/custom "type"

Thank you,

**Comment by matiasserrano** [comment]
Sorry for asking again... I'm having the same issue, the input has no name. Is there something I'm missing??

This is how I'm creating the attribute in the json:
"File": {
                                    "type": "string",
                                    "format": "url",
                                    "options": {
                                        "upload": true
                                    },
                                    "links": [
                                        {
                                            "href": "{{self}}"
                                        }
                                    ]
                                },...

Thank you
